namespace itools_source.Views
{
    partial class VirtualNumericKeyBoard
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Keyboard.VirtualKbButton virtualKbButton95 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton96 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton97 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton98 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton99 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton100 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton101 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton102 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton103 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton104 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton105 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton106 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton107 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton108 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton109 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton110 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton111 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton112 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton113 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton114 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton115 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton116 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton117 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton118 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton119 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton120 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton121 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton122 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton123 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton124 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton125 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton126 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton127 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton128 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton129 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton130 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton131 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton132 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton133 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton134 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton135 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton136 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton137 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton138 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton139 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton140 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton141 = new Keyboard.VirtualKbButton();
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this._btnClose = new Guna.UI2.WinForms.Guna2Button();
            this.virtualKeyboard = new Keyboard.VirtualKeyboard();
            this.guna2BorderlessForm_VirtualNumericKeyBoard = new Guna.UI2.WinForms.Guna2BorderlessForm(this.components);
            this.guna2Elipse_virtualKeyboard = new Guna.UI2.WinForms.Guna2Elipse(this.components);
            this.tableLayoutPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.ColumnCount = 1;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel1.Controls.Add(this._btnClose, 0, 0);
            this.tableLayoutPanel1.Controls.Add(this.virtualKeyboard, 0, 1);
            this.tableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel1.Location = new System.Drawing.Point(0, 0);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 2;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 13F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 87F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(380, 262);
            this.tableLayoutPanel1.TabIndex = 0;
            this.tableLayoutPanel1.MouseDown += new System.Windows.Forms.MouseEventHandler(this.tableLayoutPanel1_MouseDown);
            this.tableLayoutPanel1.MouseMove += new System.Windows.Forms.MouseEventHandler(this.tableLayoutPanel1_MouseMove);
            // 
            // _btnClose
            // 
            this._btnClose.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            this._btnClose.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            this._btnClose.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this._btnClose.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this._btnClose.Dock = System.Windows.Forms.DockStyle.Right;
            this._btnClose.FillColor = System.Drawing.Color.Transparent;
            this._btnClose.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._btnClose.ForeColor = System.Drawing.Color.White;
            this._btnClose.Image = global::itools_source.Properties.Resources.close_window_48;
            this._btnClose.ImageSize = new System.Drawing.Size(30, 30);
            this._btnClose.Location = new System.Drawing.Point(347, 3);
            this._btnClose.Name = "_btnClose";
            this._btnClose.Size = new System.Drawing.Size(30, 28);
            this._btnClose.TabIndex = 10;
            this._btnClose.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this._btnClose.Click += new System.EventHandler(this._btnClose_Click);
            // 
            // virtualKeyboard
            // 
            this.virtualKeyboard.AltGrState = false;
            this.virtualKeyboard.AltState = false;
            this.virtualKeyboard.BackColor = System.Drawing.Color.Transparent;
            this.virtualKeyboard.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(164)))), ((int)(((byte)(209)))), ((int)(((byte)(255)))));
            this.virtualKeyboard.BeginGradientColor = System.Drawing.Color.White;
            this.virtualKeyboard.BorderColor = System.Drawing.Color.Black;
            this.virtualKeyboard.ButtonBorderColor = System.Drawing.Color.DarkGray;
            this.virtualKeyboard.ButtonRectRadius = 6;
            this.virtualKeyboard.CapsLockState = false;
            this.virtualKeyboard.ColorPressedState = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(145)))), ((int)(((byte)(78)))));
            this.virtualKeyboard.CtrlState = false;
            this.virtualKeyboard.DecimalSeparator = '.';
            this.virtualKeyboard.Dock = System.Windows.Forms.DockStyle.Fill;
            this.virtualKeyboard.EndGradientColor = System.Drawing.Color.FromArgb(((int)(((byte)(224)))), ((int)(((byte)(224)))), ((int)(((byte)(224)))));
            virtualKbButton95.BottomFont = null;
            virtualKbButton95.BottomText = "`";
            virtualKbButton95.CanSendCommand = true;
            virtualKbButton95.Picture = null;
            virtualKbButton95.Tag = null;
            virtualKbButton95.TopFont = null;
            virtualKbButton95.TopText = "~";
            virtualKbButton96.BottomFont = null;
            virtualKbButton96.BottomText = "1";
            virtualKbButton96.CanSendCommand = true;
            virtualKbButton96.Picture = null;
            virtualKbButton96.Tag = null;
            virtualKbButton96.TopFont = null;
            virtualKbButton96.TopText = "!";
            virtualKbButton97.BottomFont = null;
            virtualKbButton97.BottomText = "2";
            virtualKbButton97.CanSendCommand = true;
            virtualKbButton97.Picture = null;
            virtualKbButton97.Tag = null;
            virtualKbButton97.TopFont = null;
            virtualKbButton97.TopText = "@";
            virtualKbButton98.BottomFont = null;
            virtualKbButton98.BottomText = "3";
            virtualKbButton98.CanSendCommand = true;
            virtualKbButton98.Picture = null;
            virtualKbButton98.Tag = null;
            virtualKbButton98.TopFont = null;
            virtualKbButton98.TopText = "#";
            virtualKbButton99.BottomFont = null;
            virtualKbButton99.BottomText = "4";
            virtualKbButton99.CanSendCommand = true;
            virtualKbButton99.Picture = null;
            virtualKbButton99.Tag = null;
            virtualKbButton99.TopFont = null;
            virtualKbButton99.TopText = "$";
            virtualKbButton100.BottomFont = null;
            virtualKbButton100.BottomText = "5";
            virtualKbButton100.CanSendCommand = true;
            virtualKbButton100.Picture = null;
            virtualKbButton100.Tag = null;
            virtualKbButton100.TopFont = null;
            virtualKbButton100.TopText = "%";
            virtualKbButton101.BottomFont = null;
            virtualKbButton101.BottomText = "6";
            virtualKbButton101.CanSendCommand = true;
            virtualKbButton101.Picture = null;
            virtualKbButton101.Tag = null;
            virtualKbButton101.TopFont = null;
            virtualKbButton101.TopText = "^";
            virtualKbButton102.BottomFont = null;
            virtualKbButton102.BottomText = "7";
            virtualKbButton102.CanSendCommand = true;
            virtualKbButton102.Picture = null;
            virtualKbButton102.Tag = null;
            virtualKbButton102.TopFont = null;
            virtualKbButton102.TopText = "&";
            virtualKbButton103.BottomFont = null;
            virtualKbButton103.BottomText = "8";
            virtualKbButton103.CanSendCommand = true;
            virtualKbButton103.Picture = null;
            virtualKbButton103.Tag = null;
            virtualKbButton103.TopFont = null;
            virtualKbButton103.TopText = "*";
            virtualKbButton104.BottomFont = null;
            virtualKbButton104.BottomText = "9";
            virtualKbButton104.CanSendCommand = true;
            virtualKbButton104.Picture = null;
            virtualKbButton104.Tag = null;
            virtualKbButton104.TopFont = null;
            virtualKbButton104.TopText = "(";
            virtualKbButton105.BottomFont = null;
            virtualKbButton105.BottomText = "0";
            virtualKbButton105.CanSendCommand = true;
            virtualKbButton105.Picture = null;
            virtualKbButton105.Tag = null;
            virtualKbButton105.TopFont = null;
            virtualKbButton105.TopText = ")";
            virtualKbButton106.BottomFont = null;
            virtualKbButton106.BottomText = "-";
            virtualKbButton106.CanSendCommand = true;
            virtualKbButton106.Picture = null;
            virtualKbButton106.Tag = null;
            virtualKbButton106.TopFont = null;
            virtualKbButton106.TopText = "_";
            virtualKbButton107.BottomFont = null;
            virtualKbButton107.BottomText = "+";
            virtualKbButton107.CanSendCommand = true;
            virtualKbButton107.Picture = null;
            virtualKbButton107.Tag = null;
            virtualKbButton107.TopFont = null;
            virtualKbButton107.TopText = "=";
            new Keyboard.ButtonsCollection().Add(virtualKbButton95);
            new Keyboard.ButtonsCollection().Add(virtualKbButton96);
            new Keyboard.ButtonsCollection().Add(virtualKbButton97);
            new Keyboard.ButtonsCollection().Add(virtualKbButton98);
            new Keyboard.ButtonsCollection().Add(virtualKbButton99);
            new Keyboard.ButtonsCollection().Add(virtualKbButton100);
            new Keyboard.ButtonsCollection().Add(virtualKbButton101);
            new Keyboard.ButtonsCollection().Add(virtualKbButton102);
            new Keyboard.ButtonsCollection().Add(virtualKbButton103);
            new Keyboard.ButtonsCollection().Add(virtualKbButton104);
            new Keyboard.ButtonsCollection().Add(virtualKbButton105);
            new Keyboard.ButtonsCollection().Add(virtualKbButton106);
            new Keyboard.ButtonsCollection().Add(virtualKbButton107);
            this.virtualKeyboard.FontColor = System.Drawing.Color.Black;
            this.virtualKeyboard.FontColorShiftDisabled = System.Drawing.Color.DimGray;
            this.virtualKeyboard.FontColorSpecialKey = System.Drawing.Color.DimGray;
            virtualKbButton108.BottomFont = null;
            virtualKbButton108.BottomText = "";
            virtualKbButton108.CanSendCommand = true;
            virtualKbButton108.Picture = null;
            virtualKbButton108.Tag = null;
            virtualKbButton108.TopFont = null;
            virtualKbButton108.TopText = "z";
            virtualKbButton109.BottomFont = null;
            virtualKbButton109.BottomText = "";
            virtualKbButton109.CanSendCommand = true;
            virtualKbButton109.Picture = null;
            virtualKbButton109.Tag = null;
            virtualKbButton109.TopFont = null;
            virtualKbButton109.TopText = "x";
            virtualKbButton110.BottomFont = null;
            virtualKbButton110.BottomText = "";
            virtualKbButton110.CanSendCommand = true;
            virtualKbButton110.Picture = null;
            virtualKbButton110.Tag = null;
            virtualKbButton110.TopFont = null;
            virtualKbButton110.TopText = "c";
            virtualKbButton111.BottomFont = null;
            virtualKbButton111.BottomText = "";
            virtualKbButton111.CanSendCommand = true;
            virtualKbButton111.Picture = null;
            virtualKbButton111.Tag = null;
            virtualKbButton111.TopFont = null;
            virtualKbButton111.TopText = "v";
            virtualKbButton112.BottomFont = null;
            virtualKbButton112.BottomText = "";
            virtualKbButton112.CanSendCommand = true;
            virtualKbButton112.Picture = null;
            virtualKbButton112.Tag = null;
            virtualKbButton112.TopFont = null;
            virtualKbButton112.TopText = "b";
            virtualKbButton113.BottomFont = null;
            virtualKbButton113.BottomText = "";
            virtualKbButton113.CanSendCommand = true;
            virtualKbButton113.Picture = null;
            virtualKbButton113.Tag = null;
            virtualKbButton113.TopFont = null;
            virtualKbButton113.TopText = "n";
            virtualKbButton114.BottomFont = null;
            virtualKbButton114.BottomText = "";
            virtualKbButton114.CanSendCommand = true;
            virtualKbButton114.Picture = null;
            virtualKbButton114.Tag = null;
            virtualKbButton114.TopFont = null;
            virtualKbButton114.TopText = "m";
            virtualKbButton115.BottomFont = null;
            virtualKbButton115.BottomText = ",";
            virtualKbButton115.CanSendCommand = true;
            virtualKbButton115.Picture = null;
            virtualKbButton115.Tag = null;
            virtualKbButton115.TopFont = null;
            virtualKbButton115.TopText = "<";
            virtualKbButton116.BottomFont = null;
            virtualKbButton116.BottomText = ".";
            virtualKbButton116.CanSendCommand = true;
            virtualKbButton116.Picture = null;
            virtualKbButton116.Tag = null;
            virtualKbButton116.TopFont = null;
            virtualKbButton116.TopText = ">";
            virtualKbButton117.BottomFont = null;
            virtualKbButton117.BottomText = "/";
            virtualKbButton117.CanSendCommand = true;
            virtualKbButton117.Picture = null;
            virtualKbButton117.Tag = null;
            virtualKbButton117.TopFont = null;
            virtualKbButton117.TopText = "?";
            new Keyboard.ButtonsCollection().Add(virtualKbButton108);
            new Keyboard.ButtonsCollection().Add(virtualKbButton109);
            new Keyboard.ButtonsCollection().Add(virtualKbButton110);
            new Keyboard.ButtonsCollection().Add(virtualKbButton111);
            new Keyboard.ButtonsCollection().Add(virtualKbButton112);
            new Keyboard.ButtonsCollection().Add(virtualKbButton113);
            new Keyboard.ButtonsCollection().Add(virtualKbButton114);
            new Keyboard.ButtonsCollection().Add(virtualKbButton115);
            new Keyboard.ButtonsCollection().Add(virtualKbButton116);
            new Keyboard.ButtonsCollection().Add(virtualKbButton117);
            this.virtualKeyboard.IsNumeric = true;
            this.virtualKeyboard.LabelFont = new System.Drawing.Font("Tahoma", 11F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.virtualKeyboard.LabelFontShiftDisabled = new System.Drawing.Font("Tahoma", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.virtualKeyboard.LabelFontSpecialKey = new System.Drawing.Font("Tahoma", 8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.virtualKeyboard.LanguageButtonBottomText = "";
            this.virtualKeyboard.LanguageButtonImage = null;
            this.virtualKeyboard.LanguageButtonTopText = "Eng";
            this.virtualKeyboard.Location = new System.Drawing.Point(3, 37);
            this.virtualKeyboard.Name = "virtualKeyboard";
            this.virtualKeyboard.NumLockState = false;
            virtualKbButton118.BottomFont = null;
            virtualKbButton118.BottomText = "";
            virtualKbButton118.CanSendCommand = true;
            virtualKbButton118.Picture = null;
            virtualKbButton118.Tag = null;
            virtualKbButton118.TopFont = null;
            virtualKbButton118.TopText = "q";
            virtualKbButton119.BottomFont = null;
            virtualKbButton119.BottomText = "";
            virtualKbButton119.CanSendCommand = true;
            virtualKbButton119.Picture = null;
            virtualKbButton119.Tag = null;
            virtualKbButton119.TopFont = null;
            virtualKbButton119.TopText = "w";
            virtualKbButton120.BottomFont = null;
            virtualKbButton120.BottomText = "";
            virtualKbButton120.CanSendCommand = true;
            virtualKbButton120.Picture = null;
            virtualKbButton120.Tag = null;
            virtualKbButton120.TopFont = null;
            virtualKbButton120.TopText = "e";
            virtualKbButton121.BottomFont = null;
            virtualKbButton121.BottomText = "";
            virtualKbButton121.CanSendCommand = true;
            virtualKbButton121.Picture = null;
            virtualKbButton121.Tag = null;
            virtualKbButton121.TopFont = null;
            virtualKbButton121.TopText = "r";
            virtualKbButton122.BottomFont = null;
            virtualKbButton122.BottomText = "";
            virtualKbButton122.CanSendCommand = true;
            virtualKbButton122.Picture = null;
            virtualKbButton122.Tag = null;
            virtualKbButton122.TopFont = null;
            virtualKbButton122.TopText = "t";
            virtualKbButton123.BottomFont = null;
            virtualKbButton123.BottomText = "";
            virtualKbButton123.CanSendCommand = true;
            virtualKbButton123.Picture = null;
            virtualKbButton123.Tag = null;
            virtualKbButton123.TopFont = null;
            virtualKbButton123.TopText = "y";
            virtualKbButton124.BottomFont = null;
            virtualKbButton124.BottomText = "";
            virtualKbButton124.CanSendCommand = true;
            virtualKbButton124.Picture = null;
            virtualKbButton124.Tag = null;
            virtualKbButton124.TopFont = null;
            virtualKbButton124.TopText = "u";
            virtualKbButton125.BottomFont = null;
            virtualKbButton125.BottomText = "";
            virtualKbButton125.CanSendCommand = true;
            virtualKbButton125.Picture = null;
            virtualKbButton125.Tag = null;
            virtualKbButton125.TopFont = null;
            virtualKbButton125.TopText = "i";
            virtualKbButton126.BottomFont = null;
            virtualKbButton126.BottomText = "";
            virtualKbButton126.CanSendCommand = true;
            virtualKbButton126.Picture = null;
            virtualKbButton126.Tag = null;
            virtualKbButton126.TopFont = null;
            virtualKbButton126.TopText = "o";
            virtualKbButton127.BottomFont = null;
            virtualKbButton127.BottomText = "";
            virtualKbButton127.CanSendCommand = true;
            virtualKbButton127.Picture = null;
            virtualKbButton127.Tag = null;
            virtualKbButton127.TopFont = null;
            virtualKbButton127.TopText = "p";
            virtualKbButton128.BottomFont = null;
            virtualKbButton128.BottomText = "[";
            virtualKbButton128.CanSendCommand = true;
            virtualKbButton128.Picture = null;
            virtualKbButton128.Tag = null;
            virtualKbButton128.TopFont = null;
            virtualKbButton128.TopText = "{";
            virtualKbButton129.BottomFont = null;
            virtualKbButton129.BottomText = "]";
            virtualKbButton129.CanSendCommand = true;
            virtualKbButton129.Picture = null;
            virtualKbButton129.Tag = null;
            virtualKbButton129.TopFont = null;
            virtualKbButton129.TopText = "}";
            virtualKbButton130.BottomFont = null;
            virtualKbButton130.BottomText = "\\";
            virtualKbButton130.CanSendCommand = true;
            virtualKbButton130.Picture = null;
            virtualKbButton130.Tag = null;
            virtualKbButton130.TopFont = null;
            virtualKbButton130.TopText = "|";
            new Keyboard.ButtonsCollection().Add(virtualKbButton118);
            new Keyboard.ButtonsCollection().Add(virtualKbButton119);
            new Keyboard.ButtonsCollection().Add(virtualKbButton120);
            new Keyboard.ButtonsCollection().Add(virtualKbButton121);
            new Keyboard.ButtonsCollection().Add(virtualKbButton122);
            new Keyboard.ButtonsCollection().Add(virtualKbButton123);
            new Keyboard.ButtonsCollection().Add(virtualKbButton124);
            new Keyboard.ButtonsCollection().Add(virtualKbButton125);
            new Keyboard.ButtonsCollection().Add(virtualKbButton126);
            new Keyboard.ButtonsCollection().Add(virtualKbButton127);
            new Keyboard.ButtonsCollection().Add(virtualKbButton128);
            new Keyboard.ButtonsCollection().Add(virtualKbButton129);
            new Keyboard.ButtonsCollection().Add(virtualKbButton130);
            this.virtualKeyboard.ShadowColor = System.Drawing.Color.LightGray;
            this.virtualKeyboard.ShadowShift = 0;
            this.virtualKeyboard.ShiftState = false;
            this.virtualKeyboard.ShowAlt = true;
            this.virtualKeyboard.ShowArrowKeys = true;
            this.virtualKeyboard.ShowBackground = true;
            this.virtualKeyboard.ShowCtrl = true;
            this.virtualKeyboard.ShowDeleteKey = true;
            this.virtualKeyboard.ShowFunctionButtons = false;
            this.virtualKeyboard.ShowLanguageButton = false;
            this.virtualKeyboard.ShowNumericButtons = false;
            this.virtualKeyboard.ShowTab = true;
            this.virtualKeyboard.Size = new System.Drawing.Size(374, 222);
            this.virtualKeyboard.TabIndex = 1;
            this.virtualKeyboard.Text = "virtualKeyboard1";
            virtualKbButton131.BottomFont = null;
            virtualKbButton131.BottomText = "";
            virtualKbButton131.CanSendCommand = true;
            virtualKbButton131.Picture = null;
            virtualKbButton131.Tag = null;
            virtualKbButton131.TopFont = null;
            virtualKbButton131.TopText = "a";
            virtualKbButton132.BottomFont = null;
            virtualKbButton132.BottomText = "";
            virtualKbButton132.CanSendCommand = true;
            virtualKbButton132.Picture = null;
            virtualKbButton132.Tag = null;
            virtualKbButton132.TopFont = null;
            virtualKbButton132.TopText = "s";
            virtualKbButton133.BottomFont = null;
            virtualKbButton133.BottomText = "";
            virtualKbButton133.CanSendCommand = true;
            virtualKbButton133.Picture = null;
            virtualKbButton133.Tag = null;
            virtualKbButton133.TopFont = null;
            virtualKbButton133.TopText = "d";
            virtualKbButton134.BottomFont = null;
            virtualKbButton134.BottomText = "";
            virtualKbButton134.CanSendCommand = true;
            virtualKbButton134.Picture = null;
            virtualKbButton134.Tag = null;
            virtualKbButton134.TopFont = null;
            virtualKbButton134.TopText = "f";
            virtualKbButton135.BottomFont = null;
            virtualKbButton135.BottomText = "";
            virtualKbButton135.CanSendCommand = true;
            virtualKbButton135.Picture = null;
            virtualKbButton135.Tag = null;
            virtualKbButton135.TopFont = null;
            virtualKbButton135.TopText = "g";
            virtualKbButton136.BottomFont = null;
            virtualKbButton136.BottomText = "";
            virtualKbButton136.CanSendCommand = true;
            virtualKbButton136.Picture = null;
            virtualKbButton136.Tag = null;
            virtualKbButton136.TopFont = null;
            virtualKbButton136.TopText = "h";
            virtualKbButton137.BottomFont = null;
            virtualKbButton137.BottomText = "";
            virtualKbButton137.CanSendCommand = true;
            virtualKbButton137.Picture = null;
            virtualKbButton137.Tag = null;
            virtualKbButton137.TopFont = null;
            virtualKbButton137.TopText = "j";
            virtualKbButton138.BottomFont = null;
            virtualKbButton138.BottomText = "";
            virtualKbButton138.CanSendCommand = true;
            virtualKbButton138.Picture = null;
            virtualKbButton138.Tag = null;
            virtualKbButton138.TopFont = null;
            virtualKbButton138.TopText = "k";
            virtualKbButton139.BottomFont = null;
            virtualKbButton139.BottomText = "";
            virtualKbButton139.CanSendCommand = true;
            virtualKbButton139.Picture = null;
            virtualKbButton139.Tag = null;
            virtualKbButton139.TopFont = null;
            virtualKbButton139.TopText = "l";
            virtualKbButton140.BottomFont = null;
            virtualKbButton140.BottomText = ";";
            virtualKbButton140.CanSendCommand = true;
            virtualKbButton140.Picture = null;
            virtualKbButton140.Tag = null;
            virtualKbButton140.TopFont = null;
            virtualKbButton140.TopText = ":";
            virtualKbButton141.BottomFont = null;
            virtualKbButton141.BottomText = "\'";
            virtualKbButton141.CanSendCommand = true;
            virtualKbButton141.Picture = null;
            virtualKbButton141.Tag = null;
            virtualKbButton141.TopFont = null;
            virtualKbButton141.TopText = "\"";
            new Keyboard.ButtonsCollection().Add(virtualKbButton131);
            new Keyboard.ButtonsCollection().Add(virtualKbButton132);
            new Keyboard.ButtonsCollection().Add(virtualKbButton133);
            new Keyboard.ButtonsCollection().Add(virtualKbButton134);
            new Keyboard.ButtonsCollection().Add(virtualKbButton135);
            new Keyboard.ButtonsCollection().Add(virtualKbButton136);
            new Keyboard.ButtonsCollection().Add(virtualKbButton137);
            new Keyboard.ButtonsCollection().Add(virtualKbButton138);
            new Keyboard.ButtonsCollection().Add(virtualKbButton139);
            new Keyboard.ButtonsCollection().Add(virtualKbButton140);
            new Keyboard.ButtonsCollection().Add(virtualKbButton141);
            // 
            // guna2BorderlessForm_VirtualNumericKeyBoard
            // 
            this.guna2BorderlessForm_VirtualNumericKeyBoard.BorderRadius = 10;
            this.guna2BorderlessForm_VirtualNumericKeyBoard.ContainerControl = this;
            this.guna2BorderlessForm_VirtualNumericKeyBoard.DockIndicatorTransparencyValue = 0.6D;
            this.guna2BorderlessForm_VirtualNumericKeyBoard.TransparentWhileDrag = true;
            // 
            // guna2Elipse_virtualKeyboard
            // 
            this.guna2Elipse_virtualKeyboard.BorderRadius = 10;
            this.guna2Elipse_virtualKeyboard.TargetControl = this.virtualKeyboard;
            // 
            // VirtualNumericKeyBoard
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 20F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(380, 262);
            this.Controls.Add(this.tableLayoutPanel1);
            this.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.Name = "VirtualNumericKeyBoard";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "VirtualNumericKeyBoard";
            this.tableLayoutPanel1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
        private Keyboard.VirtualKeyboard virtualKeyboard;
        private Guna.UI2.WinForms.Guna2BorderlessForm guna2BorderlessForm_VirtualNumericKeyBoard;
        private Guna.UI2.WinForms.Guna2Elipse guna2Elipse_virtualKeyboard;
        private Guna.UI2.WinForms.Guna2Button _btnClose;
    }
}