namespace itools_source.Views
{
    partial class VirtualKeyBoard
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Keyboard.VirtualKbButton virtualKbButton189 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton190 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton191 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton192 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton193 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton194 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton195 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton196 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton197 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton198 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton199 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton200 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton201 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton202 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton203 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton204 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton205 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton206 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton207 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton208 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton209 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton210 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton211 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton212 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton213 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton214 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton215 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton216 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton217 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton218 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton219 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton220 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton221 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton222 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton223 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton224 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton225 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton226 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton227 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton228 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton229 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton230 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton231 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton232 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton233 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton234 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton235 = new Keyboard.VirtualKbButton();
            this.tlpMain = new System.Windows.Forms.TableLayoutPanel();
            this.virtualKeyboard1 = new Keyboard.VirtualKeyboard();
            this.guna2Elipse_frmVirtualKeyBoard = new Guna.UI2.WinForms.Guna2Elipse(this.components);
            this.guna2Elipse_virtualKeyboard1 = new Guna.UI2.WinForms.Guna2Elipse(this.components);
            this._btnClose = new Guna.UI2.WinForms.Guna2Button();
            this.tlpMain.SuspendLayout();
            this.SuspendLayout();
            // 
            // tlpMain
            // 
            this.tlpMain.ColumnCount = 1;
            this.tlpMain.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tlpMain.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tlpMain.Controls.Add(this._btnClose, 0, 0);
            this.tlpMain.Controls.Add(this.virtualKeyboard1, 0, 1);
            this.tlpMain.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tlpMain.Location = new System.Drawing.Point(0, 0);
            this.tlpMain.Name = "tlpMain";
            this.tlpMain.RowCount = 2;
            this.tlpMain.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 12F));
            this.tlpMain.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 88F));
            this.tlpMain.Size = new System.Drawing.Size(650, 260);
            this.tlpMain.TabIndex = 0;
            this.tlpMain.MouseDown += new System.Windows.Forms.MouseEventHandler(this.tlpMain_MouseDown);
            this.tlpMain.MouseMove += new System.Windows.Forms.MouseEventHandler(this.tlpMain_MouseMove);
            // 
            // virtualKeyboard1
            // 
            this.virtualKeyboard1.AltGrState = false;
            this.virtualKeyboard1.AltState = false;
            this.virtualKeyboard1.BackColor = System.Drawing.Color.Transparent;
            this.virtualKeyboard1.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(164)))), ((int)(((byte)(209)))), ((int)(((byte)(255)))));
            this.virtualKeyboard1.BeginGradientColor = System.Drawing.Color.White;
            this.virtualKeyboard1.BorderColor = System.Drawing.Color.Black;
            this.virtualKeyboard1.ButtonBorderColor = System.Drawing.Color.DarkGray;
            this.virtualKeyboard1.ButtonRectRadius = 6;
            this.virtualKeyboard1.CapsLockState = false;
            this.virtualKeyboard1.ColorPressedState = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(145)))), ((int)(((byte)(78)))));
            this.virtualKeyboard1.CtrlState = false;
            this.virtualKeyboard1.DecimalSeparator = '.';
            this.virtualKeyboard1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.virtualKeyboard1.EndGradientColor = System.Drawing.Color.FromArgb(((int)(((byte)(224)))), ((int)(((byte)(224)))), ((int)(((byte)(224)))));
            virtualKbButton189.BottomFont = null;
            virtualKbButton189.BottomText = "`";
            virtualKbButton189.CanSendCommand = true;
            virtualKbButton189.Picture = null;
            virtualKbButton189.Tag = null;
            virtualKbButton189.TopFont = null;
            virtualKbButton189.TopText = "~";
            virtualKbButton190.BottomFont = null;
            virtualKbButton190.BottomText = "1";
            virtualKbButton190.CanSendCommand = true;
            virtualKbButton190.Picture = null;
            virtualKbButton190.Tag = null;
            virtualKbButton190.TopFont = null;
            virtualKbButton190.TopText = "!";
            virtualKbButton191.BottomFont = null;
            virtualKbButton191.BottomText = "2";
            virtualKbButton191.CanSendCommand = true;
            virtualKbButton191.Picture = null;
            virtualKbButton191.Tag = null;
            virtualKbButton191.TopFont = null;
            virtualKbButton191.TopText = "@";
            virtualKbButton192.BottomFont = null;
            virtualKbButton192.BottomText = "3";
            virtualKbButton192.CanSendCommand = true;
            virtualKbButton192.Picture = null;
            virtualKbButton192.Tag = null;
            virtualKbButton192.TopFont = null;
            virtualKbButton192.TopText = "#";
            virtualKbButton193.BottomFont = null;
            virtualKbButton193.BottomText = "4";
            virtualKbButton193.CanSendCommand = true;
            virtualKbButton193.Picture = null;
            virtualKbButton193.Tag = null;
            virtualKbButton193.TopFont = null;
            virtualKbButton193.TopText = "$";
            virtualKbButton194.BottomFont = null;
            virtualKbButton194.BottomText = "5";
            virtualKbButton194.CanSendCommand = true;
            virtualKbButton194.Picture = null;
            virtualKbButton194.Tag = null;
            virtualKbButton194.TopFont = null;
            virtualKbButton194.TopText = "%";
            virtualKbButton195.BottomFont = null;
            virtualKbButton195.BottomText = "6";
            virtualKbButton195.CanSendCommand = true;
            virtualKbButton195.Picture = null;
            virtualKbButton195.Tag = null;
            virtualKbButton195.TopFont = null;
            virtualKbButton195.TopText = "^";
            virtualKbButton196.BottomFont = null;
            virtualKbButton196.BottomText = "7";
            virtualKbButton196.CanSendCommand = true;
            virtualKbButton196.Picture = null;
            virtualKbButton196.Tag = null;
            virtualKbButton196.TopFont = null;
            virtualKbButton196.TopText = "&";
            virtualKbButton197.BottomFont = null;
            virtualKbButton197.BottomText = "8";
            virtualKbButton197.CanSendCommand = true;
            virtualKbButton197.Picture = null;
            virtualKbButton197.Tag = null;
            virtualKbButton197.TopFont = null;
            virtualKbButton197.TopText = "*";
            virtualKbButton198.BottomFont = null;
            virtualKbButton198.BottomText = "9";
            virtualKbButton198.CanSendCommand = true;
            virtualKbButton198.Picture = null;
            virtualKbButton198.Tag = null;
            virtualKbButton198.TopFont = null;
            virtualKbButton198.TopText = "(";
            virtualKbButton199.BottomFont = null;
            virtualKbButton199.BottomText = "0";
            virtualKbButton199.CanSendCommand = true;
            virtualKbButton199.Picture = null;
            virtualKbButton199.Tag = null;
            virtualKbButton199.TopFont = null;
            virtualKbButton199.TopText = ")";
            virtualKbButton200.BottomFont = null;
            virtualKbButton200.BottomText = "-";
            virtualKbButton200.CanSendCommand = true;
            virtualKbButton200.Picture = null;
            virtualKbButton200.Tag = null;
            virtualKbButton200.TopFont = null;
            virtualKbButton200.TopText = "_";
            virtualKbButton201.BottomFont = null;
            virtualKbButton201.BottomText = "+";
            virtualKbButton201.CanSendCommand = true;
            virtualKbButton201.Picture = null;
            virtualKbButton201.Tag = null;
            virtualKbButton201.TopFont = null;
            virtualKbButton201.TopText = "=";
            new Keyboard.ButtonsCollection().Add(virtualKbButton189);
            new Keyboard.ButtonsCollection().Add(virtualKbButton190);
            new Keyboard.ButtonsCollection().Add(virtualKbButton191);
            new Keyboard.ButtonsCollection().Add(virtualKbButton192);
            new Keyboard.ButtonsCollection().Add(virtualKbButton193);
            new Keyboard.ButtonsCollection().Add(virtualKbButton194);
            new Keyboard.ButtonsCollection().Add(virtualKbButton195);
            new Keyboard.ButtonsCollection().Add(virtualKbButton196);
            new Keyboard.ButtonsCollection().Add(virtualKbButton197);
            new Keyboard.ButtonsCollection().Add(virtualKbButton198);
            new Keyboard.ButtonsCollection().Add(virtualKbButton199);
            new Keyboard.ButtonsCollection().Add(virtualKbButton200);
            new Keyboard.ButtonsCollection().Add(virtualKbButton201);
            this.virtualKeyboard1.FontColor = System.Drawing.Color.Black;
            this.virtualKeyboard1.FontColorShiftDisabled = System.Drawing.Color.DimGray;
            this.virtualKeyboard1.FontColorSpecialKey = System.Drawing.Color.DimGray;
            virtualKbButton202.BottomFont = null;
            virtualKbButton202.BottomText = "";
            virtualKbButton202.CanSendCommand = true;
            virtualKbButton202.Picture = null;
            virtualKbButton202.Tag = null;
            virtualKbButton202.TopFont = null;
            virtualKbButton202.TopText = "z";
            virtualKbButton203.BottomFont = null;
            virtualKbButton203.BottomText = "";
            virtualKbButton203.CanSendCommand = true;
            virtualKbButton203.Picture = null;
            virtualKbButton203.Tag = null;
            virtualKbButton203.TopFont = null;
            virtualKbButton203.TopText = "x";
            virtualKbButton204.BottomFont = null;
            virtualKbButton204.BottomText = "";
            virtualKbButton204.CanSendCommand = true;
            virtualKbButton204.Picture = null;
            virtualKbButton204.Tag = null;
            virtualKbButton204.TopFont = null;
            virtualKbButton204.TopText = "c";
            virtualKbButton205.BottomFont = null;
            virtualKbButton205.BottomText = "";
            virtualKbButton205.CanSendCommand = true;
            virtualKbButton205.Picture = null;
            virtualKbButton205.Tag = null;
            virtualKbButton205.TopFont = null;
            virtualKbButton205.TopText = "v";
            virtualKbButton206.BottomFont = null;
            virtualKbButton206.BottomText = "";
            virtualKbButton206.CanSendCommand = true;
            virtualKbButton206.Picture = null;
            virtualKbButton206.Tag = null;
            virtualKbButton206.TopFont = null;
            virtualKbButton206.TopText = "b";
            virtualKbButton207.BottomFont = null;
            virtualKbButton207.BottomText = "";
            virtualKbButton207.CanSendCommand = true;
            virtualKbButton207.Picture = null;
            virtualKbButton207.Tag = null;
            virtualKbButton207.TopFont = null;
            virtualKbButton207.TopText = "n";
            virtualKbButton208.BottomFont = null;
            virtualKbButton208.BottomText = "";
            virtualKbButton208.CanSendCommand = true;
            virtualKbButton208.Picture = null;
            virtualKbButton208.Tag = null;
            virtualKbButton208.TopFont = null;
            virtualKbButton208.TopText = "m";
            virtualKbButton209.BottomFont = null;
            virtualKbButton209.BottomText = ",";
            virtualKbButton209.CanSendCommand = true;
            virtualKbButton209.Picture = null;
            virtualKbButton209.Tag = null;
            virtualKbButton209.TopFont = null;
            virtualKbButton209.TopText = "<";
            virtualKbButton210.BottomFont = null;
            virtualKbButton210.BottomText = ".";
            virtualKbButton210.CanSendCommand = true;
            virtualKbButton210.Picture = null;
            virtualKbButton210.Tag = null;
            virtualKbButton210.TopFont = null;
            virtualKbButton210.TopText = ">";
            virtualKbButton211.BottomFont = null;
            virtualKbButton211.BottomText = "/";
            virtualKbButton211.CanSendCommand = true;
            virtualKbButton211.Picture = null;
            virtualKbButton211.Tag = null;
            virtualKbButton211.TopFont = null;
            virtualKbButton211.TopText = "?";
            new Keyboard.ButtonsCollection().Add(virtualKbButton202);
            new Keyboard.ButtonsCollection().Add(virtualKbButton203);
            new Keyboard.ButtonsCollection().Add(virtualKbButton204);
            new Keyboard.ButtonsCollection().Add(virtualKbButton205);
            new Keyboard.ButtonsCollection().Add(virtualKbButton206);
            new Keyboard.ButtonsCollection().Add(virtualKbButton207);
            new Keyboard.ButtonsCollection().Add(virtualKbButton208);
            new Keyboard.ButtonsCollection().Add(virtualKbButton209);
            new Keyboard.ButtonsCollection().Add(virtualKbButton210);
            new Keyboard.ButtonsCollection().Add(virtualKbButton211);
            this.virtualKeyboard1.IsNumeric = false;
            this.virtualKeyboard1.LabelFont = new System.Drawing.Font("Tahoma", 11F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.virtualKeyboard1.LabelFontShiftDisabled = new System.Drawing.Font("Tahoma", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.virtualKeyboard1.LabelFontSpecialKey = new System.Drawing.Font("Tahoma", 8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.virtualKeyboard1.LanguageButtonBottomText = "";
            this.virtualKeyboard1.LanguageButtonImage = null;
            this.virtualKeyboard1.LanguageButtonTopText = "Eng";
            this.virtualKeyboard1.Location = new System.Drawing.Point(3, 34);
            this.virtualKeyboard1.Name = "virtualKeyboard1";
            this.virtualKeyboard1.NumLockState = false;
            virtualKbButton212.BottomFont = null;
            virtualKbButton212.BottomText = "";
            virtualKbButton212.CanSendCommand = true;
            virtualKbButton212.Picture = null;
            virtualKbButton212.Tag = null;
            virtualKbButton212.TopFont = null;
            virtualKbButton212.TopText = "q";
            virtualKbButton213.BottomFont = null;
            virtualKbButton213.BottomText = "";
            virtualKbButton213.CanSendCommand = true;
            virtualKbButton213.Picture = null;
            virtualKbButton213.Tag = null;
            virtualKbButton213.TopFont = null;
            virtualKbButton213.TopText = "w";
            virtualKbButton214.BottomFont = null;
            virtualKbButton214.BottomText = "";
            virtualKbButton214.CanSendCommand = true;
            virtualKbButton214.Picture = null;
            virtualKbButton214.Tag = null;
            virtualKbButton214.TopFont = null;
            virtualKbButton214.TopText = "e";
            virtualKbButton215.BottomFont = null;
            virtualKbButton215.BottomText = "";
            virtualKbButton215.CanSendCommand = true;
            virtualKbButton215.Picture = null;
            virtualKbButton215.Tag = null;
            virtualKbButton215.TopFont = null;
            virtualKbButton215.TopText = "r";
            virtualKbButton216.BottomFont = null;
            virtualKbButton216.BottomText = "";
            virtualKbButton216.CanSendCommand = true;
            virtualKbButton216.Picture = null;
            virtualKbButton216.Tag = null;
            virtualKbButton216.TopFont = null;
            virtualKbButton216.TopText = "t";
            virtualKbButton217.BottomFont = null;
            virtualKbButton217.BottomText = "";
            virtualKbButton217.CanSendCommand = true;
            virtualKbButton217.Picture = null;
            virtualKbButton217.Tag = null;
            virtualKbButton217.TopFont = null;
            virtualKbButton217.TopText = "y";
            virtualKbButton218.BottomFont = null;
            virtualKbButton218.BottomText = "";
            virtualKbButton218.CanSendCommand = true;
            virtualKbButton218.Picture = null;
            virtualKbButton218.Tag = null;
            virtualKbButton218.TopFont = null;
            virtualKbButton218.TopText = "u";
            virtualKbButton219.BottomFont = null;
            virtualKbButton219.BottomText = "";
            virtualKbButton219.CanSendCommand = true;
            virtualKbButton219.Picture = null;
            virtualKbButton219.Tag = null;
            virtualKbButton219.TopFont = null;
            virtualKbButton219.TopText = "i";
            virtualKbButton220.BottomFont = null;
            virtualKbButton220.BottomText = "";
            virtualKbButton220.CanSendCommand = true;
            virtualKbButton220.Picture = null;
            virtualKbButton220.Tag = null;
            virtualKbButton220.TopFont = null;
            virtualKbButton220.TopText = "o";
            virtualKbButton221.BottomFont = null;
            virtualKbButton221.BottomText = "";
            virtualKbButton221.CanSendCommand = true;
            virtualKbButton221.Picture = null;
            virtualKbButton221.Tag = null;
            virtualKbButton221.TopFont = null;
            virtualKbButton221.TopText = "p";
            virtualKbButton222.BottomFont = null;
            virtualKbButton222.BottomText = "[";
            virtualKbButton222.CanSendCommand = true;
            virtualKbButton222.Picture = null;
            virtualKbButton222.Tag = null;
            virtualKbButton222.TopFont = null;
            virtualKbButton222.TopText = "{";
            virtualKbButton223.BottomFont = null;
            virtualKbButton223.BottomText = "]";
            virtualKbButton223.CanSendCommand = true;
            virtualKbButton223.Picture = null;
            virtualKbButton223.Tag = null;
            virtualKbButton223.TopFont = null;
            virtualKbButton223.TopText = "}";
            virtualKbButton224.BottomFont = null;
            virtualKbButton224.BottomText = "\\";
            virtualKbButton224.CanSendCommand = true;
            virtualKbButton224.Picture = null;
            virtualKbButton224.Tag = null;
            virtualKbButton224.TopFont = null;
            virtualKbButton224.TopText = "|";
            new Keyboard.ButtonsCollection().Add(virtualKbButton212);
            new Keyboard.ButtonsCollection().Add(virtualKbButton213);
            new Keyboard.ButtonsCollection().Add(virtualKbButton214);
            new Keyboard.ButtonsCollection().Add(virtualKbButton215);
            new Keyboard.ButtonsCollection().Add(virtualKbButton216);
            new Keyboard.ButtonsCollection().Add(virtualKbButton217);
            new Keyboard.ButtonsCollection().Add(virtualKbButton218);
            new Keyboard.ButtonsCollection().Add(virtualKbButton219);
            new Keyboard.ButtonsCollection().Add(virtualKbButton220);
            new Keyboard.ButtonsCollection().Add(virtualKbButton221);
            new Keyboard.ButtonsCollection().Add(virtualKbButton222);
            new Keyboard.ButtonsCollection().Add(virtualKbButton223);
            new Keyboard.ButtonsCollection().Add(virtualKbButton224);
            this.virtualKeyboard1.ShadowColor = System.Drawing.Color.LightGray;
            this.virtualKeyboard1.ShadowShift = 0;
            this.virtualKeyboard1.ShiftState = false;
            this.virtualKeyboard1.ShowAlt = true;
            this.virtualKeyboard1.ShowArrowKeys = true;
            this.virtualKeyboard1.ShowBackground = true;
            this.virtualKeyboard1.ShowCtrl = true;
            this.virtualKeyboard1.ShowDeleteKey = true;
            this.virtualKeyboard1.ShowFunctionButtons = false;
            this.virtualKeyboard1.ShowLanguageButton = false;
            this.virtualKeyboard1.ShowNumericButtons = false;
            this.virtualKeyboard1.ShowTab = true;
            this.virtualKeyboard1.Size = new System.Drawing.Size(644, 223);
            this.virtualKeyboard1.TabIndex = 0;
            this.virtualKeyboard1.Text = "virtualKeyboard1";
            virtualKbButton225.BottomFont = null;
            virtualKbButton225.BottomText = "";
            virtualKbButton225.CanSendCommand = true;
            virtualKbButton225.Picture = null;
            virtualKbButton225.Tag = null;
            virtualKbButton225.TopFont = null;
            virtualKbButton225.TopText = "a";
            virtualKbButton226.BottomFont = null;
            virtualKbButton226.BottomText = "";
            virtualKbButton226.CanSendCommand = true;
            virtualKbButton226.Picture = null;
            virtualKbButton226.Tag = null;
            virtualKbButton226.TopFont = null;
            virtualKbButton226.TopText = "s";
            virtualKbButton227.BottomFont = null;
            virtualKbButton227.BottomText = "";
            virtualKbButton227.CanSendCommand = true;
            virtualKbButton227.Picture = null;
            virtualKbButton227.Tag = null;
            virtualKbButton227.TopFont = null;
            virtualKbButton227.TopText = "d";
            virtualKbButton228.BottomFont = null;
            virtualKbButton228.BottomText = "";
            virtualKbButton228.CanSendCommand = true;
            virtualKbButton228.Picture = null;
            virtualKbButton228.Tag = null;
            virtualKbButton228.TopFont = null;
            virtualKbButton228.TopText = "f";
            virtualKbButton229.BottomFont = null;
            virtualKbButton229.BottomText = "";
            virtualKbButton229.CanSendCommand = true;
            virtualKbButton229.Picture = null;
            virtualKbButton229.Tag = null;
            virtualKbButton229.TopFont = null;
            virtualKbButton229.TopText = "g";
            virtualKbButton230.BottomFont = null;
            virtualKbButton230.BottomText = "";
            virtualKbButton230.CanSendCommand = true;
            virtualKbButton230.Picture = null;
            virtualKbButton230.Tag = null;
            virtualKbButton230.TopFont = null;
            virtualKbButton230.TopText = "h";
            virtualKbButton231.BottomFont = null;
            virtualKbButton231.BottomText = "";
            virtualKbButton231.CanSendCommand = true;
            virtualKbButton231.Picture = null;
            virtualKbButton231.Tag = null;
            virtualKbButton231.TopFont = null;
            virtualKbButton231.TopText = "j";
            virtualKbButton232.BottomFont = null;
            virtualKbButton232.BottomText = "";
            virtualKbButton232.CanSendCommand = true;
            virtualKbButton232.Picture = null;
            virtualKbButton232.Tag = null;
            virtualKbButton232.TopFont = null;
            virtualKbButton232.TopText = "k";
            virtualKbButton233.BottomFont = null;
            virtualKbButton233.BottomText = "";
            virtualKbButton233.CanSendCommand = true;
            virtualKbButton233.Picture = null;
            virtualKbButton233.Tag = null;
            virtualKbButton233.TopFont = null;
            virtualKbButton233.TopText = "l";
            virtualKbButton234.BottomFont = null;
            virtualKbButton234.BottomText = ";";
            virtualKbButton234.CanSendCommand = true;
            virtualKbButton234.Picture = null;
            virtualKbButton234.Tag = null;
            virtualKbButton234.TopFont = null;
            virtualKbButton234.TopText = ":";
            virtualKbButton235.BottomFont = null;
            virtualKbButton235.BottomText = "\'";
            virtualKbButton235.CanSendCommand = true;
            virtualKbButton235.Picture = null;
            virtualKbButton235.Tag = null;
            virtualKbButton235.TopFont = null;
            virtualKbButton235.TopText = "\"";
            new Keyboard.ButtonsCollection().Add(virtualKbButton225);
            new Keyboard.ButtonsCollection().Add(virtualKbButton226);
            new Keyboard.ButtonsCollection().Add(virtualKbButton227);
            new Keyboard.ButtonsCollection().Add(virtualKbButton228);
            new Keyboard.ButtonsCollection().Add(virtualKbButton229);
            new Keyboard.ButtonsCollection().Add(virtualKbButton230);
            new Keyboard.ButtonsCollection().Add(virtualKbButton231);
            new Keyboard.ButtonsCollection().Add(virtualKbButton232);
            new Keyboard.ButtonsCollection().Add(virtualKbButton233);
            new Keyboard.ButtonsCollection().Add(virtualKbButton234);
            new Keyboard.ButtonsCollection().Add(virtualKbButton235);
            // 
            // guna2Elipse_frmVirtualKeyBoard
            // 
            this.guna2Elipse_frmVirtualKeyBoard.TargetControl = this;
            // 
            // guna2Elipse_virtualKeyboard1
            // 
            this.guna2Elipse_virtualKeyboard1.TargetControl = this.virtualKeyboard1;
            // 
            // _btnClose
            // 
            this._btnClose.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            this._btnClose.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            this._btnClose.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this._btnClose.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this._btnClose.Dock = System.Windows.Forms.DockStyle.Right;
            this._btnClose.FillColor = System.Drawing.Color.Transparent;
            this._btnClose.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._btnClose.ForeColor = System.Drawing.Color.White;
            this._btnClose.Image = global::itools_source.Properties.Resources.close_window_48;
            this._btnClose.ImageSize = new System.Drawing.Size(30, 30);
            this._btnClose.Location = new System.Drawing.Point(617, 3);
            this._btnClose.Name = "_btnClose";
            this._btnClose.Size = new System.Drawing.Size(30, 25);
            this._btnClose.TabIndex = 11;
            this._btnClose.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this._btnClose.Click += new System.EventHandler(this._btnClose_Click);
            // 
            // VirtualKeyBoard
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(650, 260);
            this.Controls.Add(this.tlpMain);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "VirtualKeyBoard";
            this.Text = "VirtualKeyBoard";
            this.tlpMain.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.TableLayoutPanel tlpMain;
        private Keyboard.VirtualKeyboard virtualKeyboard1;
        private Guna.UI2.WinForms.Guna2Elipse guna2Elipse_frmVirtualKeyBoard;
        private Guna.UI2.WinForms.Guna2Elipse guna2Elipse_virtualKeyboard1;
        private Guna.UI2.WinForms.Guna2Button _btnClose;
    }
}