namespace itools_source.Views
{
    partial class VirtualKeyBoard
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Keyboard.VirtualKbButton virtualKbButton142 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton143 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton144 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton145 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton146 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton147 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton148 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton149 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton150 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton151 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton152 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton153 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton154 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton155 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton156 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton157 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton158 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton159 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton160 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton161 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton162 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton163 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton164 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton165 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton166 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton167 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton168 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton169 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton170 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton171 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton172 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton173 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton174 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton175 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton176 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton177 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton178 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton179 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton180 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton181 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton182 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton183 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton184 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton185 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton186 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton187 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton188 = new Keyboard.VirtualKbButton();
            this.tlpMain = new System.Windows.Forms.TableLayoutPanel();
            this.guna2Elipse_frmVirtualKeyBoard = new Guna.UI2.WinForms.Guna2Elipse(this.components);
            this.guna2Elipse_virtualKeyboard1 = new Guna.UI2.WinForms.Guna2Elipse(this.components);
            this.guna2Elipse_btnClose = new Guna.UI2.WinForms.Guna2Elipse(this.components);
            this.virtualKeyboard1 = new Keyboard.VirtualKeyboard();
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this._btnClose = new Guna.UI2.WinForms.Guna2Button();
            this.btnNumeric = new Guna.UI2.WinForms.Guna2Button();
            this.tlpMain.SuspendLayout();
            this.tableLayoutPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // tlpMain
            // 
            this.tlpMain.ColumnCount = 1;
            this.tlpMain.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tlpMain.Controls.Add(this.virtualKeyboard1, 0, 1);
            this.tlpMain.Controls.Add(this.tableLayoutPanel1, 0, 0);
            this.tlpMain.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tlpMain.Location = new System.Drawing.Point(0, 0);
            this.tlpMain.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.tlpMain.Name = "tlpMain";
            this.tlpMain.RowCount = 2;
            this.tlpMain.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 15F));
            this.tlpMain.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 85F));
            this.tlpMain.Size = new System.Drawing.Size(650, 260);
            this.tlpMain.TabIndex = 0;
            this.tlpMain.MouseDown += new System.Windows.Forms.MouseEventHandler(this.tlpMain_MouseDown);
            this.tlpMain.MouseMove += new System.Windows.Forms.MouseEventHandler(this.tlpMain_MouseMove);
            // 
            // guna2Elipse_frmVirtualKeyBoard
            // 
            this.guna2Elipse_frmVirtualKeyBoard.TargetControl = this;
            // 
            // guna2Elipse_virtualKeyboard1
            // 
            this.guna2Elipse_virtualKeyboard1.TargetControl = this.virtualKeyboard1;
            // 
            // guna2Elipse_btnClose
            // 
            this.guna2Elipse_btnClose.TargetControl = this._btnClose;
            // 
            // virtualKeyboard1
            // 
            this.virtualKeyboard1.AltGrState = false;
            this.virtualKeyboard1.AltState = false;
            this.virtualKeyboard1.BackColor = System.Drawing.Color.Transparent;
            this.virtualKeyboard1.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(201)))), ((int)(((byte)(197)))));
            this.virtualKeyboard1.BeginGradientColor = System.Drawing.Color.White;
            this.virtualKeyboard1.BorderColor = System.Drawing.Color.Black;
            this.virtualKeyboard1.ButtonBorderColor = System.Drawing.Color.DarkGray;
            this.virtualKeyboard1.ButtonRectRadius = 6;
            this.virtualKeyboard1.CapsLockState = false;
            this.virtualKeyboard1.ColorPressedState = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(145)))), ((int)(((byte)(78)))));
            this.virtualKeyboard1.CtrlState = false;
            this.virtualKeyboard1.DecimalSeparator = '.';
            this.virtualKeyboard1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.virtualKeyboard1.EndGradientColor = System.Drawing.Color.FromArgb(((int)(((byte)(224)))), ((int)(((byte)(224)))), ((int)(((byte)(224)))));
            virtualKbButton142.BottomFont = null;
            virtualKbButton142.BottomText = "`";
            virtualKbButton142.CanSendCommand = true;
            virtualKbButton142.Picture = null;
            virtualKbButton142.Tag = null;
            virtualKbButton142.TopFont = null;
            virtualKbButton142.TopText = "~";
            virtualKbButton143.BottomFont = null;
            virtualKbButton143.BottomText = "1";
            virtualKbButton143.CanSendCommand = true;
            virtualKbButton143.Picture = null;
            virtualKbButton143.Tag = null;
            virtualKbButton143.TopFont = null;
            virtualKbButton143.TopText = "!";
            virtualKbButton144.BottomFont = null;
            virtualKbButton144.BottomText = "2";
            virtualKbButton144.CanSendCommand = true;
            virtualKbButton144.Picture = null;
            virtualKbButton144.Tag = null;
            virtualKbButton144.TopFont = null;
            virtualKbButton144.TopText = "@";
            virtualKbButton145.BottomFont = null;
            virtualKbButton145.BottomText = "3";
            virtualKbButton145.CanSendCommand = true;
            virtualKbButton145.Picture = null;
            virtualKbButton145.Tag = null;
            virtualKbButton145.TopFont = null;
            virtualKbButton145.TopText = "#";
            virtualKbButton146.BottomFont = null;
            virtualKbButton146.BottomText = "4";
            virtualKbButton146.CanSendCommand = true;
            virtualKbButton146.Picture = null;
            virtualKbButton146.Tag = null;
            virtualKbButton146.TopFont = null;
            virtualKbButton146.TopText = "$";
            virtualKbButton147.BottomFont = null;
            virtualKbButton147.BottomText = "5";
            virtualKbButton147.CanSendCommand = true;
            virtualKbButton147.Picture = null;
            virtualKbButton147.Tag = null;
            virtualKbButton147.TopFont = null;
            virtualKbButton147.TopText = "%";
            virtualKbButton148.BottomFont = null;
            virtualKbButton148.BottomText = "6";
            virtualKbButton148.CanSendCommand = true;
            virtualKbButton148.Picture = null;
            virtualKbButton148.Tag = null;
            virtualKbButton148.TopFont = null;
            virtualKbButton148.TopText = "^";
            virtualKbButton149.BottomFont = null;
            virtualKbButton149.BottomText = "7";
            virtualKbButton149.CanSendCommand = true;
            virtualKbButton149.Picture = null;
            virtualKbButton149.Tag = null;
            virtualKbButton149.TopFont = null;
            virtualKbButton149.TopText = "&";
            virtualKbButton150.BottomFont = null;
            virtualKbButton150.BottomText = "8";
            virtualKbButton150.CanSendCommand = true;
            virtualKbButton150.Picture = null;
            virtualKbButton150.Tag = null;
            virtualKbButton150.TopFont = null;
            virtualKbButton150.TopText = "*";
            virtualKbButton151.BottomFont = null;
            virtualKbButton151.BottomText = "9";
            virtualKbButton151.CanSendCommand = true;
            virtualKbButton151.Picture = null;
            virtualKbButton151.Tag = null;
            virtualKbButton151.TopFont = null;
            virtualKbButton151.TopText = "(";
            virtualKbButton152.BottomFont = null;
            virtualKbButton152.BottomText = "0";
            virtualKbButton152.CanSendCommand = true;
            virtualKbButton152.Picture = null;
            virtualKbButton152.Tag = null;
            virtualKbButton152.TopFont = null;
            virtualKbButton152.TopText = ")";
            virtualKbButton153.BottomFont = null;
            virtualKbButton153.BottomText = "-";
            virtualKbButton153.CanSendCommand = true;
            virtualKbButton153.Picture = null;
            virtualKbButton153.Tag = null;
            virtualKbButton153.TopFont = null;
            virtualKbButton153.TopText = "_";
            virtualKbButton154.BottomFont = null;
            virtualKbButton154.BottomText = "+";
            virtualKbButton154.CanSendCommand = true;
            virtualKbButton154.Picture = null;
            virtualKbButton154.Tag = null;
            virtualKbButton154.TopFont = null;
            virtualKbButton154.TopText = "=";
            new Keyboard.ButtonsCollection().Add(virtualKbButton142);
            new Keyboard.ButtonsCollection().Add(virtualKbButton143);
            new Keyboard.ButtonsCollection().Add(virtualKbButton144);
            new Keyboard.ButtonsCollection().Add(virtualKbButton145);
            new Keyboard.ButtonsCollection().Add(virtualKbButton146);
            new Keyboard.ButtonsCollection().Add(virtualKbButton147);
            new Keyboard.ButtonsCollection().Add(virtualKbButton148);
            new Keyboard.ButtonsCollection().Add(virtualKbButton149);
            new Keyboard.ButtonsCollection().Add(virtualKbButton150);
            new Keyboard.ButtonsCollection().Add(virtualKbButton151);
            new Keyboard.ButtonsCollection().Add(virtualKbButton152);
            new Keyboard.ButtonsCollection().Add(virtualKbButton153);
            new Keyboard.ButtonsCollection().Add(virtualKbButton154);
            this.virtualKeyboard1.FontColor = System.Drawing.Color.Black;
            this.virtualKeyboard1.FontColorShiftDisabled = System.Drawing.Color.DimGray;
            this.virtualKeyboard1.FontColorSpecialKey = System.Drawing.Color.DimGray;
            virtualKbButton155.BottomFont = null;
            virtualKbButton155.BottomText = "";
            virtualKbButton155.CanSendCommand = true;
            virtualKbButton155.Picture = null;
            virtualKbButton155.Tag = null;
            virtualKbButton155.TopFont = null;
            virtualKbButton155.TopText = "z";
            virtualKbButton156.BottomFont = null;
            virtualKbButton156.BottomText = "";
            virtualKbButton156.CanSendCommand = true;
            virtualKbButton156.Picture = null;
            virtualKbButton156.Tag = null;
            virtualKbButton156.TopFont = null;
            virtualKbButton156.TopText = "x";
            virtualKbButton157.BottomFont = null;
            virtualKbButton157.BottomText = "";
            virtualKbButton157.CanSendCommand = true;
            virtualKbButton157.Picture = null;
            virtualKbButton157.Tag = null;
            virtualKbButton157.TopFont = null;
            virtualKbButton157.TopText = "c";
            virtualKbButton158.BottomFont = null;
            virtualKbButton158.BottomText = "";
            virtualKbButton158.CanSendCommand = true;
            virtualKbButton158.Picture = null;
            virtualKbButton158.Tag = null;
            virtualKbButton158.TopFont = null;
            virtualKbButton158.TopText = "v";
            virtualKbButton159.BottomFont = null;
            virtualKbButton159.BottomText = "";
            virtualKbButton159.CanSendCommand = true;
            virtualKbButton159.Picture = null;
            virtualKbButton159.Tag = null;
            virtualKbButton159.TopFont = null;
            virtualKbButton159.TopText = "b";
            virtualKbButton160.BottomFont = null;
            virtualKbButton160.BottomText = "";
            virtualKbButton160.CanSendCommand = true;
            virtualKbButton160.Picture = null;
            virtualKbButton160.Tag = null;
            virtualKbButton160.TopFont = null;
            virtualKbButton160.TopText = "n";
            virtualKbButton161.BottomFont = null;
            virtualKbButton161.BottomText = "";
            virtualKbButton161.CanSendCommand = true;
            virtualKbButton161.Picture = null;
            virtualKbButton161.Tag = null;
            virtualKbButton161.TopFont = null;
            virtualKbButton161.TopText = "m";
            virtualKbButton162.BottomFont = null;
            virtualKbButton162.BottomText = ",";
            virtualKbButton162.CanSendCommand = true;
            virtualKbButton162.Picture = null;
            virtualKbButton162.Tag = null;
            virtualKbButton162.TopFont = null;
            virtualKbButton162.TopText = "<";
            virtualKbButton163.BottomFont = null;
            virtualKbButton163.BottomText = ".";
            virtualKbButton163.CanSendCommand = true;
            virtualKbButton163.Picture = null;
            virtualKbButton163.Tag = null;
            virtualKbButton163.TopFont = null;
            virtualKbButton163.TopText = ">";
            virtualKbButton164.BottomFont = null;
            virtualKbButton164.BottomText = "/";
            virtualKbButton164.CanSendCommand = true;
            virtualKbButton164.Picture = null;
            virtualKbButton164.Tag = null;
            virtualKbButton164.TopFont = null;
            virtualKbButton164.TopText = "?";
            new Keyboard.ButtonsCollection().Add(virtualKbButton155);
            new Keyboard.ButtonsCollection().Add(virtualKbButton156);
            new Keyboard.ButtonsCollection().Add(virtualKbButton157);
            new Keyboard.ButtonsCollection().Add(virtualKbButton158);
            new Keyboard.ButtonsCollection().Add(virtualKbButton159);
            new Keyboard.ButtonsCollection().Add(virtualKbButton160);
            new Keyboard.ButtonsCollection().Add(virtualKbButton161);
            new Keyboard.ButtonsCollection().Add(virtualKbButton162);
            new Keyboard.ButtonsCollection().Add(virtualKbButton163);
            new Keyboard.ButtonsCollection().Add(virtualKbButton164);
            this.virtualKeyboard1.IsNumeric = false;
            this.virtualKeyboard1.LabelFont = new System.Drawing.Font("Tahoma", 11F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.virtualKeyboard1.LabelFontShiftDisabled = new System.Drawing.Font("Tahoma", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.virtualKeyboard1.LabelFontSpecialKey = new System.Drawing.Font("Tahoma", 8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.virtualKeyboard1.LanguageButtonBottomText = "";
            this.virtualKeyboard1.LanguageButtonImage = null;
            this.virtualKeyboard1.LanguageButtonTopText = "Eng";
            this.virtualKeyboard1.Location = new System.Drawing.Point(4, 44);
            this.virtualKeyboard1.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.virtualKeyboard1.Name = "virtualKeyboard1";
            this.virtualKeyboard1.NumLockState = false;
            virtualKbButton165.BottomFont = null;
            virtualKbButton165.BottomText = "";
            virtualKbButton165.CanSendCommand = true;
            virtualKbButton165.Picture = null;
            virtualKbButton165.Tag = null;
            virtualKbButton165.TopFont = null;
            virtualKbButton165.TopText = "q";
            virtualKbButton166.BottomFont = null;
            virtualKbButton166.BottomText = "";
            virtualKbButton166.CanSendCommand = true;
            virtualKbButton166.Picture = null;
            virtualKbButton166.Tag = null;
            virtualKbButton166.TopFont = null;
            virtualKbButton166.TopText = "w";
            virtualKbButton167.BottomFont = null;
            virtualKbButton167.BottomText = "";
            virtualKbButton167.CanSendCommand = true;
            virtualKbButton167.Picture = null;
            virtualKbButton167.Tag = null;
            virtualKbButton167.TopFont = null;
            virtualKbButton167.TopText = "e";
            virtualKbButton168.BottomFont = null;
            virtualKbButton168.BottomText = "";
            virtualKbButton168.CanSendCommand = true;
            virtualKbButton168.Picture = null;
            virtualKbButton168.Tag = null;
            virtualKbButton168.TopFont = null;
            virtualKbButton168.TopText = "r";
            virtualKbButton169.BottomFont = null;
            virtualKbButton169.BottomText = "";
            virtualKbButton169.CanSendCommand = true;
            virtualKbButton169.Picture = null;
            virtualKbButton169.Tag = null;
            virtualKbButton169.TopFont = null;
            virtualKbButton169.TopText = "t";
            virtualKbButton170.BottomFont = null;
            virtualKbButton170.BottomText = "";
            virtualKbButton170.CanSendCommand = true;
            virtualKbButton170.Picture = null;
            virtualKbButton170.Tag = null;
            virtualKbButton170.TopFont = null;
            virtualKbButton170.TopText = "y";
            virtualKbButton171.BottomFont = null;
            virtualKbButton171.BottomText = "";
            virtualKbButton171.CanSendCommand = true;
            virtualKbButton171.Picture = null;
            virtualKbButton171.Tag = null;
            virtualKbButton171.TopFont = null;
            virtualKbButton171.TopText = "u";
            virtualKbButton172.BottomFont = null;
            virtualKbButton172.BottomText = "";
            virtualKbButton172.CanSendCommand = true;
            virtualKbButton172.Picture = null;
            virtualKbButton172.Tag = null;
            virtualKbButton172.TopFont = null;
            virtualKbButton172.TopText = "i";
            virtualKbButton173.BottomFont = null;
            virtualKbButton173.BottomText = "";
            virtualKbButton173.CanSendCommand = true;
            virtualKbButton173.Picture = null;
            virtualKbButton173.Tag = null;
            virtualKbButton173.TopFont = null;
            virtualKbButton173.TopText = "o";
            virtualKbButton174.BottomFont = null;
            virtualKbButton174.BottomText = "";
            virtualKbButton174.CanSendCommand = true;
            virtualKbButton174.Picture = null;
            virtualKbButton174.Tag = null;
            virtualKbButton174.TopFont = null;
            virtualKbButton174.TopText = "p";
            virtualKbButton175.BottomFont = null;
            virtualKbButton175.BottomText = "[";
            virtualKbButton175.CanSendCommand = true;
            virtualKbButton175.Picture = null;
            virtualKbButton175.Tag = null;
            virtualKbButton175.TopFont = null;
            virtualKbButton175.TopText = "{";
            virtualKbButton176.BottomFont = null;
            virtualKbButton176.BottomText = "]";
            virtualKbButton176.CanSendCommand = true;
            virtualKbButton176.Picture = null;
            virtualKbButton176.Tag = null;
            virtualKbButton176.TopFont = null;
            virtualKbButton176.TopText = "}";
            virtualKbButton177.BottomFont = null;
            virtualKbButton177.BottomText = "\\";
            virtualKbButton177.CanSendCommand = true;
            virtualKbButton177.Picture = null;
            virtualKbButton177.Tag = null;
            virtualKbButton177.TopFont = null;
            virtualKbButton177.TopText = "|";
            new Keyboard.ButtonsCollection().Add(virtualKbButton165);
            new Keyboard.ButtonsCollection().Add(virtualKbButton166);
            new Keyboard.ButtonsCollection().Add(virtualKbButton167);
            new Keyboard.ButtonsCollection().Add(virtualKbButton168);
            new Keyboard.ButtonsCollection().Add(virtualKbButton169);
            new Keyboard.ButtonsCollection().Add(virtualKbButton170);
            new Keyboard.ButtonsCollection().Add(virtualKbButton171);
            new Keyboard.ButtonsCollection().Add(virtualKbButton172);
            new Keyboard.ButtonsCollection().Add(virtualKbButton173);
            new Keyboard.ButtonsCollection().Add(virtualKbButton174);
            new Keyboard.ButtonsCollection().Add(virtualKbButton175);
            new Keyboard.ButtonsCollection().Add(virtualKbButton176);
            new Keyboard.ButtonsCollection().Add(virtualKbButton177);
            this.virtualKeyboard1.ShadowColor = System.Drawing.Color.LightGray;
            this.virtualKeyboard1.ShadowShift = 0;
            this.virtualKeyboard1.ShiftState = false;
            this.virtualKeyboard1.ShowAlt = true;
            this.virtualKeyboard1.ShowArrowKeys = true;
            this.virtualKeyboard1.ShowBackground = true;
            this.virtualKeyboard1.ShowCtrl = true;
            this.virtualKeyboard1.ShowDeleteKey = true;
            this.virtualKeyboard1.ShowFunctionButtons = false;
            this.virtualKeyboard1.ShowLanguageButton = false;
            this.virtualKeyboard1.ShowNumericButtons = false;
            this.virtualKeyboard1.ShowTab = true;
            this.virtualKeyboard1.Size = new System.Drawing.Size(642, 211);
            this.virtualKeyboard1.TabIndex = 0;
            this.virtualKeyboard1.Text = "virtualKeyboard1";
            virtualKbButton178.BottomFont = null;
            virtualKbButton178.BottomText = "";
            virtualKbButton178.CanSendCommand = true;
            virtualKbButton178.Picture = null;
            virtualKbButton178.Tag = null;
            virtualKbButton178.TopFont = null;
            virtualKbButton178.TopText = "a";
            virtualKbButton179.BottomFont = null;
            virtualKbButton179.BottomText = "";
            virtualKbButton179.CanSendCommand = true;
            virtualKbButton179.Picture = null;
            virtualKbButton179.Tag = null;
            virtualKbButton179.TopFont = null;
            virtualKbButton179.TopText = "s";
            virtualKbButton180.BottomFont = null;
            virtualKbButton180.BottomText = "";
            virtualKbButton180.CanSendCommand = true;
            virtualKbButton180.Picture = null;
            virtualKbButton180.Tag = null;
            virtualKbButton180.TopFont = null;
            virtualKbButton180.TopText = "d";
            virtualKbButton181.BottomFont = null;
            virtualKbButton181.BottomText = "";
            virtualKbButton181.CanSendCommand = true;
            virtualKbButton181.Picture = null;
            virtualKbButton181.Tag = null;
            virtualKbButton181.TopFont = null;
            virtualKbButton181.TopText = "f";
            virtualKbButton182.BottomFont = null;
            virtualKbButton182.BottomText = "";
            virtualKbButton182.CanSendCommand = true;
            virtualKbButton182.Picture = null;
            virtualKbButton182.Tag = null;
            virtualKbButton182.TopFont = null;
            virtualKbButton182.TopText = "g";
            virtualKbButton183.BottomFont = null;
            virtualKbButton183.BottomText = "";
            virtualKbButton183.CanSendCommand = true;
            virtualKbButton183.Picture = null;
            virtualKbButton183.Tag = null;
            virtualKbButton183.TopFont = null;
            virtualKbButton183.TopText = "h";
            virtualKbButton184.BottomFont = null;
            virtualKbButton184.BottomText = "";
            virtualKbButton184.CanSendCommand = true;
            virtualKbButton184.Picture = null;
            virtualKbButton184.Tag = null;
            virtualKbButton184.TopFont = null;
            virtualKbButton184.TopText = "j";
            virtualKbButton185.BottomFont = null;
            virtualKbButton185.BottomText = "";
            virtualKbButton185.CanSendCommand = true;
            virtualKbButton185.Picture = null;
            virtualKbButton185.Tag = null;
            virtualKbButton185.TopFont = null;
            virtualKbButton185.TopText = "k";
            virtualKbButton186.BottomFont = null;
            virtualKbButton186.BottomText = "";
            virtualKbButton186.CanSendCommand = true;
            virtualKbButton186.Picture = null;
            virtualKbButton186.Tag = null;
            virtualKbButton186.TopFont = null;
            virtualKbButton186.TopText = "l";
            virtualKbButton187.BottomFont = null;
            virtualKbButton187.BottomText = ";";
            virtualKbButton187.CanSendCommand = true;
            virtualKbButton187.Picture = null;
            virtualKbButton187.Tag = null;
            virtualKbButton187.TopFont = null;
            virtualKbButton187.TopText = ":";
            virtualKbButton188.BottomFont = null;
            virtualKbButton188.BottomText = "\'";
            virtualKbButton188.CanSendCommand = true;
            virtualKbButton188.Picture = null;
            virtualKbButton188.Tag = null;
            virtualKbButton188.TopFont = null;
            virtualKbButton188.TopText = "\"";
            new Keyboard.ButtonsCollection().Add(virtualKbButton178);
            new Keyboard.ButtonsCollection().Add(virtualKbButton179);
            new Keyboard.ButtonsCollection().Add(virtualKbButton180);
            new Keyboard.ButtonsCollection().Add(virtualKbButton181);
            new Keyboard.ButtonsCollection().Add(virtualKbButton182);
            new Keyboard.ButtonsCollection().Add(virtualKbButton183);
            new Keyboard.ButtonsCollection().Add(virtualKbButton184);
            new Keyboard.ButtonsCollection().Add(virtualKbButton185);
            new Keyboard.ButtonsCollection().Add(virtualKbButton186);
            new Keyboard.ButtonsCollection().Add(virtualKbButton187);
            new Keyboard.ButtonsCollection().Add(virtualKbButton188);
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.ColumnCount = 3;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 80F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 40F));
            this.tableLayoutPanel1.Controls.Add(this._btnClose, 2, 0);
            this.tableLayoutPanel1.Controls.Add(this.btnNumeric, 0, 0);
            this.tableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel1.Location = new System.Drawing.Point(3, 3);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 1;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(644, 33);
            this.tableLayoutPanel1.TabIndex = 1;
            // 
            // _btnClose
            // 
            this._btnClose.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            this._btnClose.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            this._btnClose.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this._btnClose.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this._btnClose.FillColor = System.Drawing.Color.Transparent;
            this._btnClose.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._btnClose.ForeColor = System.Drawing.Color.White;
            this._btnClose.Image = global::itools_source.Properties.Resources.close_window_48;
            this._btnClose.ImageSize = new System.Drawing.Size(30, 30);
            this._btnClose.Location = new System.Drawing.Point(608, 5);
            this._btnClose.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this._btnClose.Name = "_btnClose";
            this._btnClose.Size = new System.Drawing.Size(30, 23);
            this._btnClose.TabIndex = 13;
            this._btnClose.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this._btnClose.Click += new System.EventHandler(this._btnClose_Click);
            // 
            // btnNumeric
            // 
            this.btnNumeric.BorderRadius = 5;
            this.btnNumeric.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            this.btnNumeric.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            this.btnNumeric.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this.btnNumeric.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this.btnNumeric.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(23)))), ((int)(((byte)(24)))), ((int)(((byte)(37)))));
            this.btnNumeric.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnNumeric.ForeColor = System.Drawing.Color.White;
            this.btnNumeric.Location = new System.Drawing.Point(3, 3);
            this.btnNumeric.Name = "btnNumeric";
            this.btnNumeric.Size = new System.Drawing.Size(74, 27);
            this.btnNumeric.TabIndex = 14;
            this.btnNumeric.Text = "ABC";
            this.btnNumeric.Click += new System.EventHandler(this.btnNumeric_Click);
            // 
            // VirtualKeyBoard
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 20F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(101)))), ((int)(((byte)(126)))), ((int)(((byte)(129)))));
            this.ClientSize = new System.Drawing.Size(650, 260);
            this.Controls.Add(this.tlpMain);
            this.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.MaximumSize = new System.Drawing.Size(680, 280);
            this.MinimumSize = new System.Drawing.Size(650, 260);
            this.Name = "VirtualKeyBoard";
            this.Text = "VirtualKeyBoard";
            this.tlpMain.ResumeLayout(false);
            this.tableLayoutPanel1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.TableLayoutPanel tlpMain;
        private Guna.UI2.WinForms.Guna2Elipse guna2Elipse_frmVirtualKeyBoard;
        private Guna.UI2.WinForms.Guna2Elipse guna2Elipse_virtualKeyboard1;
        private Guna.UI2.WinForms.Guna2Elipse guna2Elipse_btnClose;
        private Keyboard.VirtualKeyboard virtualKeyboard1;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
        private Guna.UI2.WinForms.Guna2Button _btnClose;
        private Guna.UI2.WinForms.Guna2Button btnNumeric;
    }
}