namespace itools_source.Views
{
    partial class VirtualKeyBoard
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Keyboard.VirtualKbButton virtualKbButton1 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton2 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton3 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton4 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton5 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton6 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton7 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton8 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton9 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton10 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton11 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton12 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton13 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton14 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton15 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton16 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton17 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton18 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton19 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton20 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton21 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton22 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton23 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton24 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton25 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton26 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton27 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton28 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton29 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton30 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton31 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton32 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton33 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton34 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton35 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton36 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton37 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton38 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton39 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton40 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton41 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton42 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton43 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton44 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton45 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton46 = new Keyboard.VirtualKbButton();
            Keyboard.VirtualKbButton virtualKbButton47 = new Keyboard.VirtualKbButton();
            this.tlpMain = new System.Windows.Forms.TableLayoutPanel();
            this.virtualKeyboard1 = new Keyboard.VirtualKeyboard();
            this.tlpHeader = new System.Windows.Forms.TableLayoutPanel();
            this._btnClose = new Guna.UI2.WinForms.Guna2Button();
            this.btnNumeric = new Guna.UI2.WinForms.Guna2Button();
            this.guna2Elipse_frmVirtualKeyBoard = new Guna.UI2.WinForms.Guna2Elipse(this.components);
            this.guna2Elipse_virtualKeyboard1 = new Guna.UI2.WinForms.Guna2Elipse(this.components);
            this.guna2Elipse_btnClose = new Guna.UI2.WinForms.Guna2Elipse(this.components);
            this.tlpMain.SuspendLayout();
            this.tlpHeader.SuspendLayout();
            this.SuspendLayout();
            // 
            // tlpMain
            // 
            this.tlpMain.ColumnCount = 1;
            this.tlpMain.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tlpMain.Controls.Add(this.virtualKeyboard1, 0, 1);
            this.tlpMain.Controls.Add(this.tlpHeader, 0, 0);
            this.tlpMain.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tlpMain.Location = new System.Drawing.Point(0, 0);
            this.tlpMain.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.tlpMain.Name = "tlpMain";
            this.tlpMain.RowCount = 2;
            this.tlpMain.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 15F));
            this.tlpMain.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 85F));
            this.tlpMain.Size = new System.Drawing.Size(650, 260);
            this.tlpMain.TabIndex = 0;
            // 
            // virtualKeyboard1
            // 
            this.virtualKeyboard1.AltGrState = false;
            this.virtualKeyboard1.AltState = false;
            this.virtualKeyboard1.BackColor = System.Drawing.Color.Transparent;
            this.virtualKeyboard1.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(201)))), ((int)(((byte)(197)))));
            this.virtualKeyboard1.BeginGradientColor = System.Drawing.Color.White;
            this.virtualKeyboard1.BorderColor = System.Drawing.Color.Black;
            this.virtualKeyboard1.ButtonBorderColor = System.Drawing.Color.DarkGray;
            this.virtualKeyboard1.ButtonRectRadius = 6;
            this.virtualKeyboard1.CapsLockState = false;
            this.virtualKeyboard1.ColorPressedState = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(145)))), ((int)(((byte)(78)))));
            this.virtualKeyboard1.CtrlState = false;
            this.virtualKeyboard1.DecimalSeparator = '.';
            this.virtualKeyboard1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.virtualKeyboard1.EndGradientColor = System.Drawing.Color.FromArgb(((int)(((byte)(224)))), ((int)(((byte)(224)))), ((int)(((byte)(224)))));
            virtualKbButton1.BottomFont = null;
            virtualKbButton1.BottomText = "`";
            virtualKbButton1.CanSendCommand = true;
            virtualKbButton1.Picture = null;
            virtualKbButton1.Tag = null;
            virtualKbButton1.TopFont = null;
            virtualKbButton1.TopText = "~";
            virtualKbButton2.BottomFont = null;
            virtualKbButton2.BottomText = "1";
            virtualKbButton2.CanSendCommand = true;
            virtualKbButton2.Picture = null;
            virtualKbButton2.Tag = null;
            virtualKbButton2.TopFont = null;
            virtualKbButton2.TopText = "!";
            virtualKbButton3.BottomFont = null;
            virtualKbButton3.BottomText = "2";
            virtualKbButton3.CanSendCommand = true;
            virtualKbButton3.Picture = null;
            virtualKbButton3.Tag = null;
            virtualKbButton3.TopFont = null;
            virtualKbButton3.TopText = "@";
            virtualKbButton4.BottomFont = null;
            virtualKbButton4.BottomText = "3";
            virtualKbButton4.CanSendCommand = true;
            virtualKbButton4.Picture = null;
            virtualKbButton4.Tag = null;
            virtualKbButton4.TopFont = null;
            virtualKbButton4.TopText = "#";
            virtualKbButton5.BottomFont = null;
            virtualKbButton5.BottomText = "4";
            virtualKbButton5.CanSendCommand = true;
            virtualKbButton5.Picture = null;
            virtualKbButton5.Tag = null;
            virtualKbButton5.TopFont = null;
            virtualKbButton5.TopText = "$";
            virtualKbButton6.BottomFont = null;
            virtualKbButton6.BottomText = "5";
            virtualKbButton6.CanSendCommand = true;
            virtualKbButton6.Picture = null;
            virtualKbButton6.Tag = null;
            virtualKbButton6.TopFont = null;
            virtualKbButton6.TopText = "%";
            virtualKbButton7.BottomFont = null;
            virtualKbButton7.BottomText = "6";
            virtualKbButton7.CanSendCommand = true;
            virtualKbButton7.Picture = null;
            virtualKbButton7.Tag = null;
            virtualKbButton7.TopFont = null;
            virtualKbButton7.TopText = "^";
            virtualKbButton8.BottomFont = null;
            virtualKbButton8.BottomText = "7";
            virtualKbButton8.CanSendCommand = true;
            virtualKbButton8.Picture = null;
            virtualKbButton8.Tag = null;
            virtualKbButton8.TopFont = null;
            virtualKbButton8.TopText = "&";
            virtualKbButton9.BottomFont = null;
            virtualKbButton9.BottomText = "8";
            virtualKbButton9.CanSendCommand = true;
            virtualKbButton9.Picture = null;
            virtualKbButton9.Tag = null;
            virtualKbButton9.TopFont = null;
            virtualKbButton9.TopText = "*";
            virtualKbButton10.BottomFont = null;
            virtualKbButton10.BottomText = "9";
            virtualKbButton10.CanSendCommand = true;
            virtualKbButton10.Picture = null;
            virtualKbButton10.Tag = null;
            virtualKbButton10.TopFont = null;
            virtualKbButton10.TopText = "(";
            virtualKbButton11.BottomFont = null;
            virtualKbButton11.BottomText = "0";
            virtualKbButton11.CanSendCommand = true;
            virtualKbButton11.Picture = null;
            virtualKbButton11.Tag = null;
            virtualKbButton11.TopFont = null;
            virtualKbButton11.TopText = ")";
            virtualKbButton12.BottomFont = null;
            virtualKbButton12.BottomText = "-";
            virtualKbButton12.CanSendCommand = true;
            virtualKbButton12.Picture = null;
            virtualKbButton12.Tag = null;
            virtualKbButton12.TopFont = null;
            virtualKbButton12.TopText = "_";
            virtualKbButton13.BottomFont = null;
            virtualKbButton13.BottomText = "+";
            virtualKbButton13.CanSendCommand = true;
            virtualKbButton13.Picture = null;
            virtualKbButton13.Tag = null;
            virtualKbButton13.TopFont = null;
            virtualKbButton13.TopText = "=";
            new Keyboard.ButtonsCollection().Add(virtualKbButton1);
            new Keyboard.ButtonsCollection().Add(virtualKbButton2);
            new Keyboard.ButtonsCollection().Add(virtualKbButton3);
            new Keyboard.ButtonsCollection().Add(virtualKbButton4);
            new Keyboard.ButtonsCollection().Add(virtualKbButton5);
            new Keyboard.ButtonsCollection().Add(virtualKbButton6);
            new Keyboard.ButtonsCollection().Add(virtualKbButton7);
            new Keyboard.ButtonsCollection().Add(virtualKbButton8);
            new Keyboard.ButtonsCollection().Add(virtualKbButton9);
            new Keyboard.ButtonsCollection().Add(virtualKbButton10);
            new Keyboard.ButtonsCollection().Add(virtualKbButton11);
            new Keyboard.ButtonsCollection().Add(virtualKbButton12);
            new Keyboard.ButtonsCollection().Add(virtualKbButton13);
            this.virtualKeyboard1.FontColor = System.Drawing.Color.Black;
            this.virtualKeyboard1.FontColorShiftDisabled = System.Drawing.Color.DimGray;
            this.virtualKeyboard1.FontColorSpecialKey = System.Drawing.Color.DimGray;
            virtualKbButton14.BottomFont = null;
            virtualKbButton14.BottomText = "";
            virtualKbButton14.CanSendCommand = true;
            virtualKbButton14.Picture = null;
            virtualKbButton14.Tag = null;
            virtualKbButton14.TopFont = null;
            virtualKbButton14.TopText = "z";
            virtualKbButton15.BottomFont = null;
            virtualKbButton15.BottomText = "";
            virtualKbButton15.CanSendCommand = true;
            virtualKbButton15.Picture = null;
            virtualKbButton15.Tag = null;
            virtualKbButton15.TopFont = null;
            virtualKbButton15.TopText = "x";
            virtualKbButton16.BottomFont = null;
            virtualKbButton16.BottomText = "";
            virtualKbButton16.CanSendCommand = true;
            virtualKbButton16.Picture = null;
            virtualKbButton16.Tag = null;
            virtualKbButton16.TopFont = null;
            virtualKbButton16.TopText = "c";
            virtualKbButton17.BottomFont = null;
            virtualKbButton17.BottomText = "";
            virtualKbButton17.CanSendCommand = true;
            virtualKbButton17.Picture = null;
            virtualKbButton17.Tag = null;
            virtualKbButton17.TopFont = null;
            virtualKbButton17.TopText = "v";
            virtualKbButton18.BottomFont = null;
            virtualKbButton18.BottomText = "";
            virtualKbButton18.CanSendCommand = true;
            virtualKbButton18.Picture = null;
            virtualKbButton18.Tag = null;
            virtualKbButton18.TopFont = null;
            virtualKbButton18.TopText = "b";
            virtualKbButton19.BottomFont = null;
            virtualKbButton19.BottomText = "";
            virtualKbButton19.CanSendCommand = true;
            virtualKbButton19.Picture = null;
            virtualKbButton19.Tag = null;
            virtualKbButton19.TopFont = null;
            virtualKbButton19.TopText = "n";
            virtualKbButton20.BottomFont = null;
            virtualKbButton20.BottomText = "";
            virtualKbButton20.CanSendCommand = true;
            virtualKbButton20.Picture = null;
            virtualKbButton20.Tag = null;
            virtualKbButton20.TopFont = null;
            virtualKbButton20.TopText = "m";
            virtualKbButton21.BottomFont = null;
            virtualKbButton21.BottomText = ",";
            virtualKbButton21.CanSendCommand = true;
            virtualKbButton21.Picture = null;
            virtualKbButton21.Tag = null;
            virtualKbButton21.TopFont = null;
            virtualKbButton21.TopText = "<";
            virtualKbButton22.BottomFont = null;
            virtualKbButton22.BottomText = ".";
            virtualKbButton22.CanSendCommand = true;
            virtualKbButton22.Picture = null;
            virtualKbButton22.Tag = null;
            virtualKbButton22.TopFont = null;
            virtualKbButton22.TopText = ">";
            virtualKbButton23.BottomFont = null;
            virtualKbButton23.BottomText = "/";
            virtualKbButton23.CanSendCommand = true;
            virtualKbButton23.Picture = null;
            virtualKbButton23.Tag = null;
            virtualKbButton23.TopFont = null;
            virtualKbButton23.TopText = "?";
            new Keyboard.ButtonsCollection().Add(virtualKbButton14);
            new Keyboard.ButtonsCollection().Add(virtualKbButton15);
            new Keyboard.ButtonsCollection().Add(virtualKbButton16);
            new Keyboard.ButtonsCollection().Add(virtualKbButton17);
            new Keyboard.ButtonsCollection().Add(virtualKbButton18);
            new Keyboard.ButtonsCollection().Add(virtualKbButton19);
            new Keyboard.ButtonsCollection().Add(virtualKbButton20);
            new Keyboard.ButtonsCollection().Add(virtualKbButton21);
            new Keyboard.ButtonsCollection().Add(virtualKbButton22);
            new Keyboard.ButtonsCollection().Add(virtualKbButton23);
            this.virtualKeyboard1.IsNumeric = false;
            this.virtualKeyboard1.LabelFont = new System.Drawing.Font("Tahoma", 11F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.virtualKeyboard1.LabelFontShiftDisabled = new System.Drawing.Font("Tahoma", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.virtualKeyboard1.LabelFontSpecialKey = new System.Drawing.Font("Tahoma", 8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.virtualKeyboard1.LanguageButtonBottomText = "";
            this.virtualKeyboard1.LanguageButtonImage = null;
            this.virtualKeyboard1.LanguageButtonTopText = "Eng";
            this.virtualKeyboard1.Location = new System.Drawing.Point(4, 44);
            this.virtualKeyboard1.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.virtualKeyboard1.Name = "virtualKeyboard1";
            this.virtualKeyboard1.NumLockState = false;
            virtualKbButton24.BottomFont = null;
            virtualKbButton24.BottomText = "";
            virtualKbButton24.CanSendCommand = true;
            virtualKbButton24.Picture = null;
            virtualKbButton24.Tag = null;
            virtualKbButton24.TopFont = null;
            virtualKbButton24.TopText = "q";
            virtualKbButton25.BottomFont = null;
            virtualKbButton25.BottomText = "";
            virtualKbButton25.CanSendCommand = true;
            virtualKbButton25.Picture = null;
            virtualKbButton25.Tag = null;
            virtualKbButton25.TopFont = null;
            virtualKbButton25.TopText = "w";
            virtualKbButton26.BottomFont = null;
            virtualKbButton26.BottomText = "";
            virtualKbButton26.CanSendCommand = true;
            virtualKbButton26.Picture = null;
            virtualKbButton26.Tag = null;
            virtualKbButton26.TopFont = null;
            virtualKbButton26.TopText = "e";
            virtualKbButton27.BottomFont = null;
            virtualKbButton27.BottomText = "";
            virtualKbButton27.CanSendCommand = true;
            virtualKbButton27.Picture = null;
            virtualKbButton27.Tag = null;
            virtualKbButton27.TopFont = null;
            virtualKbButton27.TopText = "r";
            virtualKbButton28.BottomFont = null;
            virtualKbButton28.BottomText = "";
            virtualKbButton28.CanSendCommand = true;
            virtualKbButton28.Picture = null;
            virtualKbButton28.Tag = null;
            virtualKbButton28.TopFont = null;
            virtualKbButton28.TopText = "t";
            virtualKbButton29.BottomFont = null;
            virtualKbButton29.BottomText = "";
            virtualKbButton29.CanSendCommand = true;
            virtualKbButton29.Picture = null;
            virtualKbButton29.Tag = null;
            virtualKbButton29.TopFont = null;
            virtualKbButton29.TopText = "y";
            virtualKbButton30.BottomFont = null;
            virtualKbButton30.BottomText = "";
            virtualKbButton30.CanSendCommand = true;
            virtualKbButton30.Picture = null;
            virtualKbButton30.Tag = null;
            virtualKbButton30.TopFont = null;
            virtualKbButton30.TopText = "u";
            virtualKbButton31.BottomFont = null;
            virtualKbButton31.BottomText = "";
            virtualKbButton31.CanSendCommand = true;
            virtualKbButton31.Picture = null;
            virtualKbButton31.Tag = null;
            virtualKbButton31.TopFont = null;
            virtualKbButton31.TopText = "i";
            virtualKbButton32.BottomFont = null;
            virtualKbButton32.BottomText = "";
            virtualKbButton32.CanSendCommand = true;
            virtualKbButton32.Picture = null;
            virtualKbButton32.Tag = null;
            virtualKbButton32.TopFont = null;
            virtualKbButton32.TopText = "o";
            virtualKbButton33.BottomFont = null;
            virtualKbButton33.BottomText = "";
            virtualKbButton33.CanSendCommand = true;
            virtualKbButton33.Picture = null;
            virtualKbButton33.Tag = null;
            virtualKbButton33.TopFont = null;
            virtualKbButton33.TopText = "p";
            virtualKbButton34.BottomFont = null;
            virtualKbButton34.BottomText = "[";
            virtualKbButton34.CanSendCommand = true;
            virtualKbButton34.Picture = null;
            virtualKbButton34.Tag = null;
            virtualKbButton34.TopFont = null;
            virtualKbButton34.TopText = "{";
            virtualKbButton35.BottomFont = null;
            virtualKbButton35.BottomText = "]";
            virtualKbButton35.CanSendCommand = true;
            virtualKbButton35.Picture = null;
            virtualKbButton35.Tag = null;
            virtualKbButton35.TopFont = null;
            virtualKbButton35.TopText = "}";
            virtualKbButton36.BottomFont = null;
            virtualKbButton36.BottomText = "\\";
            virtualKbButton36.CanSendCommand = true;
            virtualKbButton36.Picture = null;
            virtualKbButton36.Tag = null;
            virtualKbButton36.TopFont = null;
            virtualKbButton36.TopText = "|";
            new Keyboard.ButtonsCollection().Add(virtualKbButton24);
            new Keyboard.ButtonsCollection().Add(virtualKbButton25);
            new Keyboard.ButtonsCollection().Add(virtualKbButton26);
            new Keyboard.ButtonsCollection().Add(virtualKbButton27);
            new Keyboard.ButtonsCollection().Add(virtualKbButton28);
            new Keyboard.ButtonsCollection().Add(virtualKbButton29);
            new Keyboard.ButtonsCollection().Add(virtualKbButton30);
            new Keyboard.ButtonsCollection().Add(virtualKbButton31);
            new Keyboard.ButtonsCollection().Add(virtualKbButton32);
            new Keyboard.ButtonsCollection().Add(virtualKbButton33);
            new Keyboard.ButtonsCollection().Add(virtualKbButton34);
            new Keyboard.ButtonsCollection().Add(virtualKbButton35);
            new Keyboard.ButtonsCollection().Add(virtualKbButton36);
            this.virtualKeyboard1.ShadowColor = System.Drawing.Color.LightGray;
            this.virtualKeyboard1.ShadowShift = 0;
            this.virtualKeyboard1.ShiftState = false;
            this.virtualKeyboard1.ShowAlt = true;
            this.virtualKeyboard1.ShowArrowKeys = true;
            this.virtualKeyboard1.ShowBackground = true;
            this.virtualKeyboard1.ShowCtrl = true;
            this.virtualKeyboard1.ShowDeleteKey = true;
            this.virtualKeyboard1.ShowFunctionButtons = false;
            this.virtualKeyboard1.ShowLanguageButton = false;
            this.virtualKeyboard1.ShowNumericButtons = false;
            this.virtualKeyboard1.ShowTab = true;
            this.virtualKeyboard1.Size = new System.Drawing.Size(642, 211);
            this.virtualKeyboard1.TabIndex = 0;
            this.virtualKeyboard1.Text = "virtualKeyboard1";
            virtualKbButton37.BottomFont = null;
            virtualKbButton37.BottomText = "";
            virtualKbButton37.CanSendCommand = true;
            virtualKbButton37.Picture = null;
            virtualKbButton37.Tag = null;
            virtualKbButton37.TopFont = null;
            virtualKbButton37.TopText = "a";
            virtualKbButton38.BottomFont = null;
            virtualKbButton38.BottomText = "";
            virtualKbButton38.CanSendCommand = true;
            virtualKbButton38.Picture = null;
            virtualKbButton38.Tag = null;
            virtualKbButton38.TopFont = null;
            virtualKbButton38.TopText = "s";
            virtualKbButton39.BottomFont = null;
            virtualKbButton39.BottomText = "";
            virtualKbButton39.CanSendCommand = true;
            virtualKbButton39.Picture = null;
            virtualKbButton39.Tag = null;
            virtualKbButton39.TopFont = null;
            virtualKbButton39.TopText = "d";
            virtualKbButton40.BottomFont = null;
            virtualKbButton40.BottomText = "";
            virtualKbButton40.CanSendCommand = true;
            virtualKbButton40.Picture = null;
            virtualKbButton40.Tag = null;
            virtualKbButton40.TopFont = null;
            virtualKbButton40.TopText = "f";
            virtualKbButton41.BottomFont = null;
            virtualKbButton41.BottomText = "";
            virtualKbButton41.CanSendCommand = true;
            virtualKbButton41.Picture = null;
            virtualKbButton41.Tag = null;
            virtualKbButton41.TopFont = null;
            virtualKbButton41.TopText = "g";
            virtualKbButton42.BottomFont = null;
            virtualKbButton42.BottomText = "";
            virtualKbButton42.CanSendCommand = true;
            virtualKbButton42.Picture = null;
            virtualKbButton42.Tag = null;
            virtualKbButton42.TopFont = null;
            virtualKbButton42.TopText = "h";
            virtualKbButton43.BottomFont = null;
            virtualKbButton43.BottomText = "";
            virtualKbButton43.CanSendCommand = true;
            virtualKbButton43.Picture = null;
            virtualKbButton43.Tag = null;
            virtualKbButton43.TopFont = null;
            virtualKbButton43.TopText = "j";
            virtualKbButton44.BottomFont = null;
            virtualKbButton44.BottomText = "";
            virtualKbButton44.CanSendCommand = true;
            virtualKbButton44.Picture = null;
            virtualKbButton44.Tag = null;
            virtualKbButton44.TopFont = null;
            virtualKbButton44.TopText = "k";
            virtualKbButton45.BottomFont = null;
            virtualKbButton45.BottomText = "";
            virtualKbButton45.CanSendCommand = true;
            virtualKbButton45.Picture = null;
            virtualKbButton45.Tag = null;
            virtualKbButton45.TopFont = null;
            virtualKbButton45.TopText = "l";
            virtualKbButton46.BottomFont = null;
            virtualKbButton46.BottomText = ";";
            virtualKbButton46.CanSendCommand = true;
            virtualKbButton46.Picture = null;
            virtualKbButton46.Tag = null;
            virtualKbButton46.TopFont = null;
            virtualKbButton46.TopText = ":";
            virtualKbButton47.BottomFont = null;
            virtualKbButton47.BottomText = "\'";
            virtualKbButton47.CanSendCommand = true;
            virtualKbButton47.Picture = null;
            virtualKbButton47.Tag = null;
            virtualKbButton47.TopFont = null;
            virtualKbButton47.TopText = "\"";
            new Keyboard.ButtonsCollection().Add(virtualKbButton37);
            new Keyboard.ButtonsCollection().Add(virtualKbButton38);
            new Keyboard.ButtonsCollection().Add(virtualKbButton39);
            new Keyboard.ButtonsCollection().Add(virtualKbButton40);
            new Keyboard.ButtonsCollection().Add(virtualKbButton41);
            new Keyboard.ButtonsCollection().Add(virtualKbButton42);
            new Keyboard.ButtonsCollection().Add(virtualKbButton43);
            new Keyboard.ButtonsCollection().Add(virtualKbButton44);
            new Keyboard.ButtonsCollection().Add(virtualKbButton45);
            new Keyboard.ButtonsCollection().Add(virtualKbButton46);
            new Keyboard.ButtonsCollection().Add(virtualKbButton47);
            // 
            // tlpHeader
            // 
            this.tlpHeader.ColumnCount = 3;
            this.tlpHeader.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 80F));
            this.tlpHeader.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tlpHeader.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 40F));
            this.tlpHeader.Controls.Add(this._btnClose, 2, 0);
            this.tlpHeader.Controls.Add(this.btnNumeric, 0, 0);
            this.tlpHeader.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tlpHeader.Location = new System.Drawing.Point(3, 3);
            this.tlpHeader.Name = "tlpHeader";
            this.tlpHeader.RowCount = 1;
            this.tlpHeader.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tlpHeader.Size = new System.Drawing.Size(644, 33);
            this.tlpHeader.TabIndex = 1;
            this.tlpHeader.MouseDown += new System.Windows.Forms.MouseEventHandler(this.tlpHeader_MouseDown);
            this.tlpHeader.MouseMove += new System.Windows.Forms.MouseEventHandler(this.tlpHeader_MouseMove);
            // 
            // _btnClose
            // 
            this._btnClose.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            this._btnClose.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            this._btnClose.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this._btnClose.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this._btnClose.FillColor = System.Drawing.Color.Transparent;
            this._btnClose.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._btnClose.ForeColor = System.Drawing.Color.White;
            this._btnClose.Image = global::itools_source.Properties.Resources.close_window_48;
            this._btnClose.ImageSize = new System.Drawing.Size(30, 30);
            this._btnClose.Location = new System.Drawing.Point(608, 5);
            this._btnClose.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this._btnClose.Name = "_btnClose";
            this._btnClose.Size = new System.Drawing.Size(30, 23);
            this._btnClose.TabIndex = 13;
            this._btnClose.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this._btnClose.Click += new System.EventHandler(this._btnClose_Click);
            // 
            // btnNumeric
            // 
            this.btnNumeric.BorderRadius = 5;
            this.btnNumeric.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            this.btnNumeric.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            this.btnNumeric.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this.btnNumeric.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this.btnNumeric.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(23)))), ((int)(((byte)(24)))), ((int)(((byte)(37)))));
            this.btnNumeric.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnNumeric.ForeColor = System.Drawing.Color.White;
            this.btnNumeric.Location = new System.Drawing.Point(3, 3);
            this.btnNumeric.Name = "btnNumeric";
            this.btnNumeric.Size = new System.Drawing.Size(74, 27);
            this.btnNumeric.TabIndex = 14;
            this.btnNumeric.Text = "ABC";
            this.btnNumeric.Click += new System.EventHandler(this.btnNumeric_Click);
            // 
            // guna2Elipse_frmVirtualKeyBoard
            // 
            this.guna2Elipse_frmVirtualKeyBoard.TargetControl = this;
            // 
            // guna2Elipse_virtualKeyboard1
            // 
            this.guna2Elipse_virtualKeyboard1.TargetControl = this.virtualKeyboard1;
            // 
            // guna2Elipse_btnClose
            // 
            this.guna2Elipse_btnClose.TargetControl = this._btnClose;
            // 
            // VirtualKeyBoard
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 20F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(101)))), ((int)(((byte)(126)))), ((int)(((byte)(129)))));
            this.ClientSize = new System.Drawing.Size(650, 260);
            this.Controls.Add(this.tlpMain);
            this.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.MaximumSize = new System.Drawing.Size(680, 280);
            this.MinimumSize = new System.Drawing.Size(650, 260);
            this.Name = "VirtualKeyBoard";
            this.Text = "VirtualKeyBoard";
            this.tlpMain.ResumeLayout(false);
            this.tlpHeader.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.TableLayoutPanel tlpMain;
        private Guna.UI2.WinForms.Guna2Elipse guna2Elipse_frmVirtualKeyBoard;
        private Guna.UI2.WinForms.Guna2Elipse guna2Elipse_virtualKeyboard1;
        private Guna.UI2.WinForms.Guna2Elipse guna2Elipse_btnClose;
        private Keyboard.VirtualKeyboard virtualKeyboard1;
        private System.Windows.Forms.TableLayoutPanel tlpHeader;
        private Guna.UI2.WinForms.Guna2Button _btnClose;
        private Guna.UI2.WinForms.Guna2Button btnNumeric;
    }
}